The AWR report consists of snapshots of performance and other data. By default Oracle takes a snapshot at the top of every hour. AWR reports are generated by analyzing the data between two snapshots. The blocking statement can do the same thing by specifying a begin and end snap ID restricting the blocking analysis to that time period.

You can use this query to show the snapshots in your AWR system.

select
    dbid,
    instance_number,
    snap_id,
    to_char(begin_interval_time, 'YYYY-MM-DD HH24:MI:SS') begin_interval_time,
    to_char(end_interval_time, 'YYYY-MM-DD HH24:MI:SS') end_interval_time
from
    dba_hist_snapshot
order by
    begin_interval_time desc;
