
SET SERVEROUTPUT ON

declare
  type table_varchar  is table of varchar2(50);
  var_table_varchar  table_varchar;
  V_USER varchar2(50);
begin

  dbms_output.put_line('');
  dbms_output.put_line('SET CREDENTIALS: UTEC AND DESARROLLO');
  dbms_output.put_line('----------------');

  execute immediate 'ALTER USER UTEC IDENTIFIED BY &2';
  execute immediate 'ALTER USER DESARROLLO IDENTIFIED BY &3';

end;
/

declare
  type table_varchar  is table of varchar2(50);
  var_table_varchar  table_varchar;
  V_STATUS varchar2(50);
begin

  dbms_output.put_line('');
  select count(*) INTO V_STATUS from dba_objects where STATUS='INVALID';
  dbms_output.put_line('INVALID OBJECTS:' || V_STATUS);
  dbms_output.put_line('----------------');

end;
/


declare

  V_STATUS varchar2(50);
begin

  dbms_output.put_line('');
  dbms_output.put_line('RECOMPILE INVALID OBJECTS:');
  dbms_output.put_line('----------------');

  for schema_to_recompile in (select UNIQUE owner from dba_objects where STATUS='INVALID')
  loop
    dbms_output.put_line('Schema to recompile: ' || ' - ' || schema_to_recompile.owner);
    DBMS_UTILITY.compile_schema(schema => schema_to_recompile.owner);
  end loop;

  for schema_to_recompile in (select UNIQUE owner from dba_objects where STATUS='INVALID')
  loop
    dbms_output.put_line('Schema to recompile: ' || ' - ' || schema_to_recompile.owner);
    DBMS_UTILITY.compile_schema(schema => schema_to_recompile.owner);
  end loop;

end;
/

declare
  type table_varchar  is table of varchar2(50);
  var_table_varchar  table_varchar;
  V_STATUS varchar2(50);
begin

  dbms_output.put_line('');
  select count(*) INTO V_STATUS from dba_objects where STATUS='INVALID';
  dbms_output.put_line('INVALID OBJECTS:' || V_STATUS);
  dbms_output.put_line('----------------');

end;
/


update GENERAL.gen_persona set username = SUBSTR(username,1,INSTR(username, '@', 1))|| '_' || TO_CHAR( codpersona)||'_'  ||'test.com'
where username  like '%@%';
COMMIT;


UPDATE CONFIGURACION.CON_REPORTES_UNITIME set URL_LINK=REPLACE(URL_LINK, 'https:////analytics.utec.edu.pe', 'https:////analyticsqa.utec.edu.pe')
where isdeleted='N';


UPDATE CONFIGURACION.CON_REPORTES_UNITIME set URL_LINK=REPLACE(URL_LINK, '5q9eOgLW3g6MldFw-TM6F-gBmp87FsrJslmySp9T', '1b9a5d82-da15-11e7-9296-cec278b6b50a')
where isdeleted='N';


UPDATE SEGURIDAD.SEG_OPCION SET RUTAREDIRECCION='https:////matriculaqa.utec.edu.pe'
WHERE  CODOPCION=173;


update SEGURIDAD.SEG_OPCION set RUTAREDIRECCION='http://asistenciaqa.utec.edu.penew?value=marcadoAula'
where OPCIONPADRE = 341 and codopcion='342';


update SEGURIDAD.SEG_OPCION set RUTAREDIRECCION='http://asistenciaqa.utec.edu.penew?value=reporteAsistencia'
where OPCIONPADRE = 341 and codopcion='343';


update SEGURIDAD.SEG_OPCION set RUTAREDIRECCION='http://asistenciaqa.utec.edu.penew?value=modificarAsistencia'
where OPCIONPADRE = 341 and codopcion='344';

UPDATE CONFIGURACION.CON_REPORTES_UNITIME SET URL_LINK = REPLACE(CONFIGURACION.CON_REPORTES_UNITIME.URL_LINK, '104.154.58.120:8080', '104.197.115.186:9500');


UPDATE CONFIGURACION.CON_REPORTES_UNITIME SET URL_LINK = REPLACE(CONFIGURACION.CON_REPORTES_UNITIME.URL_LINK, '13b9a4c0-5849-4740-b843-80e5d3505b02', 'd30ef02c-7fb1-4e00-a74b-82501bb2c695');

--Para tramite de solicitud de constancias y certificados
UPDATE CONFIGURACION.CON_FILE_SERVER SET KEYFILESERVER = '3f413f94-e869-4dec-bb82-8067d05a3d23', IDSTORAGE = '1BStWzQbQ5F-5zAU3N4MEJlGe9cxZNTQc' WHERE IDFILESERVER = 'TRAMITE-CONST-CERTI-FOTOS';

UPDATE CONFIGURACION.CON_FILE_SERVER SET KEYFILESERVER = '98c75cda-dcf2-4a4d-a5e0-28c4b0c1bf75', IDSTORAGE = '1GI1LbLUzjevzmijfttC1rznzInGgQJXD' WHERE IDFILESERVER = 'TRAMITE-CONST-CERTI-PLANTILLAS-PDF';

UPDATE CONFIGURACION.CON_FILE_SERVER SET KEYFILESERVER = '5199c4f6-55f3-4805-8570-3a82dc00b955', IDSTORAGE = '1tIP5Qqu-DHLMNGhCIImRcVRkDPXhyzoR' WHERE IDFILESERVER = 'TRAMITE-CONST-CERTI-DOCUMENTOS';

UPDATE CONFIGURACION.CON_CATALOGO_DOCUM_ACAD SET CORREONOTIFICACION = 'counter.alumnos_@test_com._utec.edu.pe';

UPDATE CONFIGURACION.CON_CATEG_PAGOS_ERP_NOTIF SET URLSERVICIO = 'https://apiqa.utec.edu.pesolicitud-api-2v1notificarpago';

UPDATE CONFIGURACION.CON_DATOS_PAGO SET responseurl = 'http://intranetqa.utec.edu.peconfirmacion-pago', CONFIRMATIONURL = 'http://104.197.190.191:9000pasarela-apiv1publicpaymentrespuestaconfirmacion', WEBCHECKOUTURL = 'https://sandbox.checkout.payulatam.comppp-web-gateway-payu', MERCHANTID = '508029',ACCOUNTID = '512323',TEST = '1';

UPDATE UTEC.SEG_APLICACION_CLIENT SET CLIENT = 'dc5e69bb-19c9-410c-8458-764686b8b95b.utecapps.edu.pe', CLIENTSECRET = '$2a$10$PfDs83cAK.d3r6p5LUiFOe1Z1dE9NJkoHky6hdk4urfsoHwly7fcO', USERMODIFY = USERINSERT WHERE DISPLAYNAME = 'pasarela-api-server-client';

UPDATE UTEC.SEG_APLICACION_CLIENT SET CLIENT = '3eef0dd7-1806-4a09-8069-9ca964e94cd9.utecapps.edu.pe', CLIENTSECRET = '$2a$10$.hYLR4Nv3gM.9fyTW5w0lu764FWzS6mtdFmSxSrG9oUSiCvHIz.', USERMODIFY = USERINSERT WHERE DISPLAYNAME = 'netsuite-api-server-client';

COMMIT;


DECLARE
  INTRANET VARCHAR2(300) := 'intranet.';
  INTRANETQA VARCHAR2(300) := 'intranetqa.';
  V_RUTANUEVA VARCHAR2(300);
  V_TEMPORAL_RUTAS VARCHAR2(200);
  CURSOR C_RUTA IS select rutaredireccion from  SEGURIDAD.SEG_OPCION where rutaredireccion like '%intranet.%' ;
BEGIN
 OPEN C_RUTA ;
 LOOP
    FETCH C_RUTA INTO V_TEMPORAL_RUTAS ;
          EXIT WHEN C_RUTA%NOTFOUND ;
          DBMS_OUTPUT.PUT_LINE(V_TEMPORAL_RUTAS);
          SELECT REPLACE( V_TEMPORAL_RUTAS,INTRANET,INTRANETQA) INTO V_RUTANUEVA FROM DUAL;
          UPDATE SEGURIDAD.SEG_OPCION SET RUTAREDIRECCION = V_RUTANUEVA WHERE RUTAREDIRECCION=V_TEMPORAL_RUTAS;
                  commit;
  END LOOP ;
   CLOSE C_RUTA;
    EXCEPTION
    WHEN OTHERS
      THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/


DECLARE
  INTRANET VARCHAR2(300) := 'matricula.';
  INTRANETQA VARCHAR2(300) := 'matriculaqa.';
  V_RUTANUEVA VARCHAR2(300);
  V_TEMPORAL_RUTAS VARCHAR2(200);
  CURSOR C_RUTA IS select rutaredireccion from  SEGURIDAD.SEG_OPCION where rutaredireccion like '%intranet.%' ;
BEGIN
 OPEN C_RUTA ;
 LOOP
    FETCH C_RUTA INTO V_TEMPORAL_RUTAS ;
          EXIT WHEN C_RUTA%NOTFOUND ;
          DBMS_OUTPUT.PUT_LINE(V_TEMPORAL_RUTAS);
          SELECT REPLACE( V_TEMPORAL_RUTAS,INTRANET,INTRANETQA) INTO V_RUTANUEVA FROM DUAL;
          UPDATE SEGURIDAD.SEG_OPCION SET RUTAREDIRECCION = V_RUTANUEVA WHERE RUTAREDIRECCION=V_TEMPORAL_RUTAS;
                  commit;
  END LOOP ;
   CLOSE C_RUTA;
    EXCEPTION
    WHEN OTHERS
      THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/


DECLARE
  INTRANET VARCHAR2(300) := 'obligaciones.';
  INTRANETQA VARCHAR2(300) := 'obligacionesqa.';
  V_RUTANUEVA VARCHAR2(300);
  V_TEMPORAL_RUTAS VARCHAR2(200);
  CURSOR C_RUTA IS select rutaredireccion from  SEGURIDAD.SEG_OPCION where rutaredireccion like '%intranet.%' ;
BEGIN
 OPEN C_RUTA ;
 LOOP
    FETCH C_RUTA INTO V_TEMPORAL_RUTAS ;
          EXIT WHEN C_RUTA%NOTFOUND ;
          DBMS_OUTPUT.PUT_LINE(V_TEMPORAL_RUTAS);
          SELECT REPLACE( V_TEMPORAL_RUTAS,INTRANET,INTRANETQA) INTO V_RUTANUEVA FROM DUAL;
          UPDATE SEGURIDAD.SEG_OPCION SET RUTAREDIRECCION = V_RUTANUEVA WHERE RUTAREDIRECCION=V_TEMPORAL_RUTAS;
                  commit;
  END LOOP ;
   CLOSE C_RUTA;
    EXCEPTION
    WHEN OTHERS
      THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/


DECLARE
  INTRANET VARCHAR2(300) := 'asistencia.';
  INTRANETQA VARCHAR2(300) := 'asistenciaqa.';
  V_RUTANUEVA VARCHAR2(300);
  V_TEMPORAL_RUTAS VARCHAR2(200);
  CURSOR C_RUTA IS select rutaredireccion from  SEGURIDAD.SEG_OPCION where rutaredireccion like '%intranet.%' ;
BEGIN
 OPEN C_RUTA ;
 LOOP
    FETCH C_RUTA INTO V_TEMPORAL_RUTAS ;
          EXIT WHEN C_RUTA%NOTFOUND ;
          DBMS_OUTPUT.PUT_LINE(V_TEMPORAL_RUTAS);
          SELECT REPLACE( V_TEMPORAL_RUTAS,INTRANET,INTRANETQA) INTO V_RUTANUEVA FROM DUAL;
          UPDATE SEGURIDAD.SEG_OPCION SET RUTAREDIRECCION = V_RUTANUEVA WHERE RUTAREDIRECCION=V_TEMPORAL_RUTAS;
                  commit;
  END LOOP ;
   CLOSE C_RUTA;
    EXCEPTION
    WHEN OTHERS
      THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

declare
  type table_varchar  is table of varchar2(50);
  var_table_varchar  table_varchar;
  V_USER varchar2(50) := 'UTEC';
begin

  dbms_output.put_line('');
  dbms_output.put_line('REPLICATE SYNONYMS');
  dbms_output.put_line('----------------');


        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_ASISTENCIA" for "AUDITORIA"."A_ACA_ALUMNO_ASISTENCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_ASISTENCIA_TIPO" for "AUDITORIA"."A_ACA_ALUMNO_ASISTENCIA_TIPO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_AVANCE_ACADEMICO" for "AUDITORIA"."A_ACA_ALUMNO_AVANCE_ACADEMICO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_CONVALIDA_DOCU" for "AUDITORIA"."A_ACA_ALUMNO_CONVALIDA_DOCU"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_CONVALIDA_DOCU_DE" for "AUDITORIA"."A_ACA_ALUMNO_CONVALIDA_DOCU_DE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_EVALUACION" for "AUDITORIA"."A_ACA_ALUMNO_EVALUACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_EVALUACION_NOTAS" for "AUDITORIA"."A_ACA_ALUMNO_EVALUACION_NOTAS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_EXAMEN_EXONERA" for "AUDITORIA"."A_ACA_ALUMNO_EXAMEN_EXONERA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_EXAMEN_NOTAS" for "AUDITORIA"."A_ACA_ALUMNO_EXAMEN_NOTAS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_IMPEDIMENTO" for "AUDITORIA"."A_ACA_ALUMNO_IMPEDIMENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_MALLA" for "AUDITORIA"."A_ACA_ALUMNO_MALLA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_MALLA_ACTIVIDAD" for "AUDITORIA"."A_ACA_ALUMNO_MALLA_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_MALLA_CONVALIDA" for "AUDITORIA"."A_ACA_ALUMNO_MALLA_CONVALIDA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_MATRICULA" for "AUDITORIA"."A_ACA_ALUMNO_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_MATRICULA_CURSO" for "AUDITORIA"."A_ACA_ALUMNO_MATRICULA_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_MATRICULA_DEMANDA" for "AUDITORIA"."A_ACA_ALUMNO_MATRICULA_DEMANDA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_PROD_NIVELACION" for "AUDITORIA"."A_ACA_ALUMNO_PROD_NIVELACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_RESTRIC_DEMANDA" for "AUDITORIA"."A_ACA_ALUMNO_RESTRIC_DEMANDA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_SANCION" for "AUDITORIA"."A_ACA_ALUMNO_SANCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_ALUMNO_SANCION_MODIFICA" for "AUDITORIA"."A_ACA_ALUMNO_SANCION_MODIFICA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_CURSO_SESION_ASISTENCIA" for "AUDITORIA"."A_ACA_CURSO_SESION_ASISTENCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_DOCENTE_ASISTENCIA" for "AUDITORIA"."A_ACA_DOCENTE_ASISTENCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_IMPEDIMENTO" for "AUDITORIA"."A_ACA_IMPEDIMENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_SESION_ASISTENCIA_MODIFI" for "AUDITORIA"."A_ACA_SESION_ASISTENCIA_MODIFI"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_SESION_EVALUACION_MODIFI" for "AUDITORIA"."A_ACA_SESION_EVALUACION_MODIFI"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_SOLICITUD_TRAMITE" for "AUDITORIA"."A_ACA_SOLICITUD_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_SOLICITUDTRAMITE_CURSO" for "AUDITORIA"."A_ACA_SOLICITUDTRAMITE_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_ACA_TUTOR_ALUMNO_MATRICULA" for "AUDITORIA"."A_ACA_TUTOR_ALUMNO_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_COM_OFERTA" for "AUDITORIA"."A_COM_OFERTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_COM_OFERTA_AREA_FUNCIONAL" for "AUDITORIA"."A_COM_OFERTA_AREA_FUNCIONAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_COM_OFERTA_SEDE" for "AUDITORIA"."A_COM_OFERTA_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_ACTIVIDAD" for "AUDITORIA"."A_CON_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_AGRUPACION" for "AUDITORIA"."A_CON_AGRUPACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_AGRUPACION_ACTIVIDAD" for "AUDITORIA"."A_CON_AGRUPACION_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_ALERTA" for "AUDITORIA"."A_CON_ALERTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CATALOGO_DOCUM_ACAD" for "AUDITORIA"."A_CON_CATALOGO_DOCUM_ACAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CATEGORIA_ELECTIVO" for "AUDITORIA"."A_CON_CATEGORIA_ELECTIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CATEGORIA_PRODUCTO_MALLA" for "AUDITORIA"."A_CON_CATEGORIA_PRODUCTO_MALLA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CLASE_ALERTA" for "AUDITORIA"."A_CON_CLASE_ALERTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_COMPLEMENTO_ACTIVIDAD" for "AUDITORIA"."A_CON_COMPLEMENTO_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CRITERIO_DESEMPENIO" for "AUDITORIA"."A_CON_CRITERIO_DESEMPENIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO" for "AUDITORIA"."A_CON_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_BIBLIOGRAFIA" for "AUDITORIA"."A_CON_CURSO_BIBLIOGRAFIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_EQUIPAMIENTO" for "AUDITORIA"."A_CON_CURSO_EQUIPAMIENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_EXT_EQUIV" for "AUDITORIA"."A_CON_CURSO_EXT_EQUIV"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_EXT_EQUIV_RANGO" for "AUDITORIA"."A_CON_CURSO_EXT_EQUIV_RANGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_METODOLOGIA" for "AUDITORIA"."A_CON_CURSO_METODOLOGIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_NOTA_DETALLE" for "AUDITORIA"."A_CON_CURSO_NOTA_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_OBJETIVO" for "AUDITORIA"."A_CON_CURSO_OBJETIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_OBJETIVO_TEMA" for "AUDITORIA"."A_CON_CURSO_OBJETIVO_TEMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_RECHAZADO_MOTIVO" for "AUDITORIA"."A_CON_CURSO_RECHAZADO_MOTIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_SESION" for "AUDITORIA"."A_CON_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_SESION_CICLO" for "AUDITORIA"."A_CON_CURSO_SESION_CICLO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_TEMA" for "AUDITORIA"."A_CON_CURSO_TEMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_TIPO_NOTA" for "AUDITORIA"."A_CON_CURSO_TIPO_NOTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_CURSO_VERSION" for "AUDITORIA"."A_CON_CURSO_VERSION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_DETALLE_EXAMEN" for "AUDITORIA"."A_CON_DETALLE_EXAMEN"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_ENTIDAD" for "AUDITORIA"."A_CON_ENTIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_ENTIDAD_PARAMETRO" for "AUDITORIA"."A_CON_ENTIDAD_PARAMETRO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_ESTADO_TRAMITE" for "AUDITORIA"."A_CON_ESTADO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_ESTADOTRAMITE_TIPOTRAMIT" for "AUDITORIA"."A_CON_ESTADOTRAMITE_TIPOTRAMIT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_EXAMEN_EXONERACION" for "AUDITORIA"."A_CON_EXAMEN_EXONERACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_GRUPO_PROGRAMA" for "AUDITORIA"."A_CON_GRUPO_PROGRAMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_MALLA" for "AUDITORIA"."A_CON_MALLA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_MALLA_ACTIVIDAD" for "AUDITORIA"."A_CON_MALLA_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_MALLA_ACTIVIDAD_TEMA" for "AUDITORIA"."A_CON_MALLA_ACTIVIDAD_TEMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_MALLA_CONVALIDACION" for "AUDITORIA"."A_CON_MALLA_CONVALIDACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_MALLA_CURSO_UNICO_DEM" for "AUDITORIA"."A_CON_MALLA_CURSO_UNICO_DEM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_MENCION" for "AUDITORIA"."A_CON_MENCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_MENCION_CURSO" for "AUDITORIA"."A_CON_MENCION_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_PARAM_ENUM" for "AUDITORIA"."A_CON_PARAM_ENUM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_PARAM_ENUM_DETALLE" for "AUDITORIA"."A_CON_PARAM_ENUM_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_PARAM_ESCALAR" for "AUDITORIA"."A_CON_PARAM_ESCALAR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_PARAM_RANGO" for "AUDITORIA"."A_CON_PARAM_RANGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_PARAMETRO" for "AUDITORIA"."A_CON_PARAMETRO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_PRODUCTO" for "AUDITORIA"."A_CON_PRODUCTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_PROGRAMA" for "AUDITORIA"."A_CON_PROGRAMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_REGLA_CURSO_UNICO" for "AUDITORIA"."A_CON_REGLA_CURSO_UNICO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CONFIGURACION.CON_REPORTES_UNITIME" for "AUDITORIA"."A_CONFIGURACION.CON_REPORTES_UNITIME"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_RESERVADO_CURSO_ELECTIVO" for "AUDITORIA"."A_CON_RESERVADO_CURSO_ELECTIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_RESULTADO" for "AUDITORIA"."A_CON_RESULTADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_TIPO_NOTA" for "AUDITORIA"."A_CON_TIPO_NOTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_TIPO_TRAMITE" for "AUDITORIA"."A_CON_TIPO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_CON_VALOR_PARAM" for "AUDITORIA"."A_CON_VALOR_PARAM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_EGR_PRACTICA_PREPR_DETALLE" for "AUDITORIA"."A_EGR_PRACTICA_PREPR_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_EGR_PRACTICA_PREPROFESIONAL" for "AUDITORIA"."A_EGR_PRACTICA_PREPROFESIONAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_ASIGNACION" for "AUDITORIA"."A_FIN_ASIGNACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_BENEFICIO" for "AUDITORIA"."A_FIN_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_DETALLE_PAGO_TRAMITE" for "AUDITORIA"."A_FIN_DETALLE_PAGO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_DETALLE_TRANSAC_PAGO" for "AUDITORIA"."A_FIN_DETALLE_TRANSAC_PAGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_EJECUCION" for "AUDITORIA"."A_FIN_EJECUCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_EJECUCION_DETALLE" for "AUDITORIA"."A_FIN_EJECUCION_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_ESCALA" for "AUDITORIA"."A_FIN_ESCALA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_MODALIDAD" for "AUDITORIA"."A_FIN_MODALIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_OPERACION" for "AUDITORIA"."A_FIN_OPERACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_OPERACION_TIPO_BENEFICIO" for "AUDITORIA"."A_FIN_OPERACION_TIPO_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_PAGO_DETALLE_BOLETA" for "AUDITORIA"."A_FIN_PAGO_DETALLE_BOLETA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_PAGO_DETALLE_CATEGORIA" for "AUDITORIA"."A_FIN_PAGO_DETALLE_CATEGORIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_PROCESO" for "AUDITORIA"."A_FIN_PROCESO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_TASA_BENEFICIO" for "AUDITORIA"."A_FIN_TASA_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_TIPO_BENEFICIO" for "AUDITORIA"."A_FIN_TIPO_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_FIN_TRANSAC_PENDIENTE_RESP" for "AUDITORIA"."A_FIN_TRANSAC_PENDIENTE_RESP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_ALUMNO" for "AUDITORIA"."A_GEN_ALUMNO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_ALUMNO_CARNET" for "AUDITORIA"."A_GEN_ALUMNO_CARNET"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_AREA_FUNCIONAL" for "AUDITORIA"."A_GEN_AREA_FUNCIONAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_AULA" for "AUDITORIA"."A_GEN_AULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_EMPLEADO" for "AUDITORIA"."A_GEN_EMPLEADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_INSTITUCION" for "AUDITORIA"."A_GEN_INSTITUCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_INSTITUCION_EXTERNA" for "AUDITORIA"."A_GEN_INSTITUCION_EXTERNA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_INSTITUCION_SEDE" for "AUDITORIA"."A_GEN_INSTITUCION_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_INSTITUCION_SEDE_CONTACT" for "AUDITORIA"."A_GEN_INSTITUCION_SEDE_CONTACT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_MAESTRO_TABLAS" for "AUDITORIA"."A_GEN_MAESTRO_TABLAS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_MAESTRO_TABLAS_DETALLE" for "AUDITORIA"."A_GEN_MAESTRO_TABLAS_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_NOTIFICACION" for "AUDITORIA"."A_GEN_NOTIFICACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_PERSONA" for "AUDITORIA"."A_GEN_PERSONA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_PERSONA_FORMA_CONTACTAR" for "AUDITORIA"."A_GEN_PERSONA_FORMA_CONTACTAR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_SOLICITUD" for "AUDITORIA"."A_GEN_SOLICITUD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_SOLICITUD_ADJUNTA_DOC" for "AUDITORIA"."A_GEN_SOLICITUD_ADJUNTA_DOC"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_GEN_SOLICITUDDETALLE" for "AUDITORIA"."A_GEN_SOLICITUDDETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_MAT_CONFIGURACION_MATRICULA" for "AUDITORIA"."A_MAT_CONFIGURACION_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_MAT_MATRICULA_TURNO" for "AUDITORIA"."A_MAT_MATRICULA_TURNO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_MAT_MATRICULA_TURNO_ALUMNO" for "AUDITORIA"."A_MAT_MATRICULA_TURNO_ALUMNO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_MAT_PERMISO_MATRICULA" for "AUDITORIA"."A_MAT_PERMISO_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PMA_ALUMNO_CURSO" for "AUDITORIA"."A_PMA_ALUMNO_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PMA_ALUMNO_CURSO_SESION" for "AUDITORIA"."A_PMA_ALUMNO_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PMA_CONFI_PREMATRICULA" for "AUDITORIA"."A_PMA_CONFI_PREMATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CLASE_PROGRAMADA" for "AUDITORIA"."A_PRO_CLASE_PROGRAMADA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_EVALUACION" for "AUDITORIA"."A_PRO_CURSO_EVALUACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_FORMULA" for "AUDITORIA"."A_PRO_CURSO_FORMULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_FORMULA_BITACORA" for "AUDITORIA"."A_PRO_CURSO_FORMULA_BITACORA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_PERIODO" for "AUDITORIA"."A_PRO_CURSO_PERIODO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_SECCION" for "AUDITORIA"."A_PRO_CURSO_SECCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_SESION" for "AUDITORIA"."A_PRO_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_SESION_REAPERTURA" for "AUDITORIA"."A_PRO_CURSO_SESION_REAPERTURA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_CURSO_TIPONOTA" for "AUDITORIA"."A_PRO_CURSO_TIPONOTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_DIA_FERIADO" for "AUDITORIA"."A_PRO_DIA_FERIADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_DOCENTE_REASIGNACION" for "AUDITORIA"."A_PRO_DOCENTE_REASIGNACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_EVALUACION_PROGRAMADA" for "AUDITORIA"."A_PRO_EVALUACION_PROGRAMADA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_EXAMEN_PROGRAMADO" for "AUDITORIA"."A_PRO_EXAMEN_PROGRAMADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_MALLA_VIGENTE" for "AUDITORIA"."A_PRO_MALLA_VIGENTE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_MATRICULA_CURSO_SESION" for "AUDITORIA"."A_PRO_MATRICULA_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_PERIODO" for "AUDITORIA"."A_PRO_PERIODO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_PERIODO_RANGO_PRODUCTO" for "AUDITORIA"."A_PRO_PERIODO_RANGO_PRODUCTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_PERIODO_RESULTADOCIERRE" for "AUDITORIA"."A_PRO_PERIODO_RESULTADOCIERRE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_PERIODORANGO" for "AUDITORIA"."A_PRO_PERIODORANGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_RESERVA_AULA" for "AUDITORIA"."A_PRO_RESERVA_AULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_SEMANA_DICTADO_PERIODO" for "AUDITORIA"."A_PRO_SEMANA_DICTADO_PERIODO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_SOLICITUD_PROCESO_BATCH" for "AUDITORIA"."A_PRO_SOLICITUD_PROCESO_BATCH"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_PRO_TRAMITE" for "AUDITORIA"."A_PRO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_APLICACION" for "AUDITORIA"."A_SEG_APLICACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_APLICACION_CLIENT" for "AUDITORIA"."A_SEG_APLICACION_CLIENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_APLICACION_OPCION_EXT" for "AUDITORIA"."A_SEG_APLICACION_OPCION_EXT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_MODULO" for "AUDITORIA"."A_SEG_MODULO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_MODULO_APLICACION" for "AUDITORIA"."A_SEG_MODULO_APLICACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_OPCION" for "AUDITORIA"."A_SEG_OPCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_OPCION_ROL_SEDE" for "AUDITORIA"."A_SEG_OPCION_ROL_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_ROL" for "AUDITORIA"."A_SEG_ROL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_ROL_MODULO" for "AUDITORIA"."A_SEG_ROL_MODULO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_ROL_SEDE" for "AUDITORIA"."A_SEG_ROL_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_SEG_ROL_SEDE_PERSONA" for "AUDITORIA"."A_SEG_ROL_SEDE_PERSONA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_TRA_SOLIC_DOCUMENTO_ACAD" for "AUDITORIA"."A_TRA_SOLIC_DOCUMENTO_ACAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_TRA_SOLICITUD_TRAMITE_ADJUNT" for "AUDITORIA"."A_TRA_SOLICITUD_TRAMITE_ADJUNT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_TRA_SOLICITUD_TRAMITE_DETALL" for "AUDITORIA"."A_TRA_SOLICITUD_TRAMITE_DETALL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_TRA_SOLICITUD_TRAMITE_EVENTO" for "AUDITORIA"."A_TRA_SOLICITUD_TRAMITE_EVENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_TRA_SOLICITUD_TRAMITE_EXTEND" for "AUDITORIA"."A_TRA_SOLICITUD_TRAMITE_EXTEND"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."A_UTECSUP_INTEGRATION_AUDIT" for "AUDITORIA"."A_UTECSUP_INTEGRATION_AUDIT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_ASISTENCIA" for "ACADEMICO"."ACA_ALUMNO_ASISTENCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_ASISTENCIA_TIPO" for "ACADEMICO"."ACA_ALUMNO_ASISTENCIA_TIPO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_AVANCE_ACADEMICO" for "ACADEMICO"."ACA_ALUMNO_AVANCE_ACADEMICO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_CONVALIDA_DOCU" for "ACADEMICO"."ACA_ALUMNO_CONVALIDA_DOCU"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_CONVALIDA_DOCU_DET" for "ACADEMICO"."ACA_ALUMNO_CONVALIDA_DOCU_DET"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_EVALUACION" for "ACADEMICO"."ACA_ALUMNO_EVALUACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_EVALUACION_NOTAS" for "ACADEMICO"."ACA_ALUMNO_EVALUACION_NOTAS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_EXAMEN_EXONERACION" for "ACADEMICO"."ACA_ALUMNO_EXAMEN_EXONERACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_EXAMEN_NOTAS" for "ACADEMICO"."ACA_ALUMNO_EXAMEN_NOTAS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_IMPEDIMENTO" for "ACADEMICO"."ACA_ALUMNO_IMPEDIMENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_MALLA" for "ACADEMICO"."ACA_ALUMNO_MALLA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_MALLA_ACTIVIDAD" for "ACADEMICO"."ACA_ALUMNO_MALLA_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_MALLA_CONVALIDA" for "ACADEMICO"."ACA_ALUMNO_MALLA_CONVALIDA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_MATRICULA" for "ACADEMICO"."ACA_ALUMNO_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_MATRICULA_CURSO" for "ACADEMICO"."ACA_ALUMNO_MATRICULA_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_MATRICULA_DEMANDA" for "ACADEMICO"."ACA_ALUMNO_MATRICULA_DEMANDA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_PRIORIDAD_MANUAL" for "ACADEMICO"."ACA_ALUMNO_PRIORIDAD_MANUAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_PRODUCTO_NIVELACION" for "ACADEMICO"."ACA_ALUMNO_PRODUCTO_NIVELACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_RESTRIC_DEMANDA" for "ACADEMICO"."ACA_ALUMNO_RESTRIC_DEMANDA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_SANCION" for "ACADEMICO"."ACA_ALUMNO_SANCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_ALUMNO_SANCION_MODIFICA" for "ACADEMICO"."ACA_ALUMNO_SANCION_MODIFICA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_CURSO_SESION_ASISTENCIA" for "ACADEMICO"."ACA_CURSO_SESION_ASISTENCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_DOCENTE_ASISTENCIA" for "ACADEMICO"."ACA_DOCENTE_ASISTENCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_IMPEDIMENTO" for "ACADEMICO"."ACA_IMPEDIMENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_SESION_ASISTENCIA_MODIFICA" for "ACADEMICO"."ACA_SESION_ASISTENCIA_MODIFICA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_SESION_EVALUACION_MODIFICA" for "ACADEMICO"."ACA_SESION_EVALUACION_MODIFICA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_SOLICITUD_TRAMITE" for "ACADEMICO"."ACA_SOLICITUD_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_SOLICITUDTRAMITE_CURSO" for "ACADEMICO"."ACA_SOLICITUDTRAMITE_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACA_TUTOR_ALUMNO_MATRICULA" for "ACADEMICO"."ACA_TUTOR_ALUMNO_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACAD_CLASS_SEQ" for "TIMETABLE"."ACAD_CLASS_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACADEMIC_AREA" for "TIMETABLE"."ACADEMIC_AREA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACADEMIC_AREA_SEQ" for "TIMETABLE"."ACADEMIC_AREA_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ACADEMIC_CLASSIFICATION" for "TIMETABLE"."ACADEMIC_CLASSIFICATION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."APPLICATION_CONFIG" for "TIMETABLE"."APPLICATION_CONFIG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ASSIGNED_INSTRUCTORS" for "TIMETABLE"."ASSIGNED_INSTRUCTORS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ASSIGNED_ROOMS" for "TIMETABLE"."ASSIGNED_ROOMS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ASSIGNMENT" for "TIMETABLE"."ASSIGNMENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ASSIGNMENT_SEQ" for "TIMETABLE"."ASSIGNMENT_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."BUILDING" for "TIMETABLE"."BUILDING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."BUILDING_PREF" for "TIMETABLE"."BUILDING_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."BUILDING_SEQ" for "TIMETABLE"."BUILDING_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CALENDAR" for "CALENDAR"."CALENDAR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CALENDAR_SEQ" for "CALENDAR"."CALENDAR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CHANGE_LOG" for "TIMETABLE"."CHANGE_LOG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CLASS_" for "TIMETABLE"."CLASS_"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CLASS_INSTRUCTOR" for "TIMETABLE"."CLASS_INSTRUCTOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CLASS_INSTRUCTOR_SEQ" for "TIMETABLE"."CLASS_INSTRUCTOR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CLASS_WAITLIST" for "TIMETABLE"."CLASS_WAITLIST"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CLUSTER_DISCOVERY" for "TIMETABLE"."CLUSTER_DISCOVERY"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COM_OFERTA" for "COMERCIAL"."COM_OFERTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COM_OFERTA_AREA_FUNCIONAL" for "COMERCIAL"."COM_OFERTA_AREA_FUNCIONAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COM_OFERTA_SEDE" for "COMERCIAL"."COM_OFERTA_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ACTIVIDAD" for "CONFIGURACION"."CON_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_AGRUPACION" for "CONFIGURACION"."CON_AGRUPACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_AGRUPACION_ACTIVIDAD" for "CONFIGURACION"."CON_AGRUPACION_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ALERTA" for "CONFIGURACION"."CON_ALERTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ALERTA_PERSONALIZADA" for "CONFIGURACION"."CON_ALERTA_PERSONALIZADA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ALERTA_RECEPTOR" for "CONFIGURACION"."CON_ALERTA_RECEPTOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_AREAFUNCI_TRAMINOTIF" for "CONFIGURACION"."CON_AREAFUNCI_TRAMINOTIF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CATALOGO_DOCUM_ACAD" for "CONFIGURACION"."CON_CATALOGO_DOCUM_ACAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CATEG_PAGOS_ERP_NOTIF" for "CONFIGURACION"."CON_CATEG_PAGOS_ERP_NOTIF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CATEGORIA_ELECTIVO" for "CONFIGURACION"."CON_CATEGORIA_ELECTIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CATEGORIA_PRODUCTO_MALLA" for "CONFIGURACION"."CON_CATEGORIA_PRODUCTO_MALLA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CLASE_ALERTA" for "CONFIGURACION"."CON_CLASE_ALERTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_COMPLEMENTO_ACTIVIDAD" for "CONFIGURACION"."CON_COMPLEMENTO_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CRITERIO_DESEMPENIO" for "CONFIGURACION"."CON_CRITERIO_DESEMPENIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO" for "CONFIGURACION"."CON_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_BIBLIOGRAFIA" for "CONFIGURACION"."CON_CURSO_BIBLIOGRAFIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_EQUIPAMIENTO" for "CONFIGURACION"."CON_CURSO_EQUIPAMIENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_EXT_EQUIV" for "CONFIGURACION"."CON_CURSO_EXT_EQUIV"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_EXT_EQUIV_RANGO" for "CONFIGURACION"."CON_CURSO_EXT_EQUIV_RANGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_METODOLOGIA" for "CONFIGURACION"."CON_CURSO_METODOLOGIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_NOTA_DETALLE" for "CONFIGURACION"."CON_CURSO_NOTA_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_OBJETIVO" for "CONFIGURACION"."CON_CURSO_OBJETIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_OBJETIVO_TEMA" for "CONFIGURACION"."CON_CURSO_OBJETIVO_TEMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_RECHAZADO_MOTIVO" for "CONFIGURACION"."CON_CURSO_RECHAZADO_MOTIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_SESION" for "CONFIGURACION"."CON_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_SESION_CICLO" for "CONFIGURACION"."CON_CURSO_SESION_CICLO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_TEMA" for "CONFIGURACION"."CON_CURSO_TEMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_TIPO_NOTA" for "CONFIGURACION"."CON_CURSO_TIPO_NOTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_CURSO_VERSION" for "CONFIGURACION"."CON_CURSO_VERSION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_DATOS_ESTADO_PAGO" for "CONFIGURACION"."CON_DATOS_ESTADO_PAGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_DATOS_ESTADO_PAGO_S" for "CONFIGURACION"."CON_DATOS_ESTADO_PAGO_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_DATOS_MEDIOS_DE_PAGO" for "CONFIGURACION"."CON_DATOS_MEDIOS_DE_PAGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_DATOS_MEDIOS_DE_PAGO_S" for "CONFIGURACION"."CON_DATOS_MEDIOS_DE_PAGO_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_DATOS_PAGO" for "CONFIGURACION"."CON_DATOS_PAGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_DATOS_PAGO_S" for "CONFIGURACION"."CON_DATOS_PAGO_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_DETALLE_EXAMEN" for "CONFIGURACION"."CON_DETALLE_EXAMEN"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ENTIDAD" for "CONFIGURACION"."CON_ENTIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ENTIDAD_PARAMETRO" for "CONFIGURACION"."CON_ENTIDAD_PARAMETRO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_EQUIVALENCIA" for "CONFIGURACION"."CON_EQUIVALENCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ESTADO_TRAMITE" for "CONFIGURACION"."CON_ESTADO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ESTADOTRAMITE_TIPOTRAMITE" for "CONFIGURACION"."CON_ESTADOTRAMITE_TIPOTRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ESTATRAM_TIPOTRAM_B" for "CONFIGURACION"."CON_ESTATRAM_TIPOTRAM_B"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_ESTATRAM_TIPOTRAM_S" for "CONFIGURACION"."CON_ESTATRAM_TIPOTRAM_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_EXAMEN_EXONERACION" for "CONFIGURACION"."CON_EXAMEN_EXONERACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_GRUPO_PROGRAMA" for "CONFIGURACION"."CON_GRUPO_PROGRAMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA" for "CONFIGURACION"."CON_MALLA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_ACT_TEMA_CRITERIO" for "CONFIGURACION"."CON_MALLA_ACT_TEMA_CRITERIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_ACTIVIDAD" for "CONFIGURACION"."CON_MALLA_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_ACTIVIDAD_PRERREQ" for "CONFIGURACION"."CON_MALLA_ACTIVIDAD_PRERREQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_ACTIVIDAD_TEMA" for "CONFIGURACION"."CON_MALLA_ACTIVIDAD_TEMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_CONV_ACTIVIDAD" for "CONFIGURACION"."CON_MALLA_CONV_ACTIVIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_CONVALIDACION" for "CONFIGURACION"."CON_MALLA_CONVALIDACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_CURSO_UNICO_DEMANDA" for "CONFIGURACION"."CON_MALLA_CURSO_UNICO_DEMANDA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MALLA_RESULTADO" for "CONFIGURACION"."CON_MALLA_RESULTADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MENCION" for "CONFIGURACION"."CON_MENCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_MENCION_CURSO" for "CONFIGURACION"."CON_MENCION_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PAQUETE" for "CONFIGURACION"."CON_PAQUETE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PARAM_ENUM" for "CONFIGURACION"."CON_PARAM_ENUM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PARAM_ENUM_DETALLE" for "CONFIGURACION"."CON_PARAM_ENUM_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PARAM_ESCALAR" for "CONFIGURACION"."CON_PARAM_ESCALAR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PARAM_RANGO" for "CONFIGURACION"."CON_PARAM_RANGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PARAMETRO" for "CONFIGURACION"."CON_PARAMETRO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PAYU_CONSUMER" for "CONFIGURACION"."CON_PAYU_CONSUMER"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PAYU_CONSUMER_S" for "CONFIGURACION"."CON_PAYU_CONSUMER_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PRODUCTO" for "CONFIGURACION"."CON_PRODUCTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_PROGRAMA" for "CONFIGURACION"."CON_PROGRAMA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_REGLA_CURSO_UNICO" for "CONFIGURACION"."CON_REGLA_CURSO_UNICO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CONFIGURACION.CON_REPORTES_UNITIME" for "CONFIGURACION"."CONFIGURACION.CON_REPORTES_UNITIME"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_RESERVADO_CURSO_ELECTIVO" for "CONFIGURACION"."CON_RESERVADO_CURSO_ELECTIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_RESULTADO" for "CONFIGURACION"."CON_RESULTADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_SOLICITUD_TRAMITE" for "CONFIGURACION"."CON_SOLICITUD_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_TIPO_NOTA" for "CONFIGURACION"."CON_TIPO_NOTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_TIPO_TRAMITE" for "CONFIGURACION"."CON_TIPO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_TRAMITE" for "CONFIGURACION"."CON_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CON_VALOR_PARAM" for "CONFIGURACION"."CON_VALOR_PARAM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CONSTRAINT_INFO" for "TIMETABLE"."CONSTRAINT_INFO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_CATALOG" for "TIMETABLE"."COURSE_CATALOG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_CREDIT_TYPE" for "TIMETABLE"."COURSE_CREDIT_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_CREDIT_UNIT_CONFIG" for "TIMETABLE"."COURSE_CREDIT_UNIT_CONFIG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_CREDIT_UNIT_TYPE" for "TIMETABLE"."COURSE_CREDIT_UNIT_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_DEMAND" for "TIMETABLE"."COURSE_DEMAND"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_OFFERING" for "TIMETABLE"."COURSE_OFFERING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_REQUEST" for "TIMETABLE"."COURSE_REQUEST"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_REQUEST_OPTION" for "TIMETABLE"."COURSE_REQUEST_OPTION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_SUBPART_CREDIT" for "TIMETABLE"."COURSE_SUBPART_CREDIT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."COURSE_TYPE" for "TIMETABLE"."COURSE_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CRS_CREDIT_UNIG_CFG_SEQ" for "TIMETABLE"."CRS_CREDIT_UNIG_CFG_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CRS_OFFR_DEMAND_SEQ" for "TIMETABLE"."CRS_OFFR_DEMAND_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CRS_OFFR_SEQ" for "TIMETABLE"."CRS_OFFR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CRSE_CREDIT_FORMAT" for "TIMETABLE"."CRSE_CREDIT_FORMAT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CURRICULUM" for "TIMETABLE"."CURRICULUM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CURRICULUM_CLASF" for "TIMETABLE"."CURRICULUM_CLASF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CURRICULUM_COURSE" for "TIMETABLE"."CURRICULUM_COURSE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CURRICULUM_COURSE_GROUP" for "TIMETABLE"."CURRICULUM_COURSE_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CURRICULUM_GROUP" for "TIMETABLE"."CURRICULUM_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CURRICULUM_MAJOR" for "TIMETABLE"."CURRICULUM_MAJOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."CURRICULUM_RULE" for "TIMETABLE"."CURRICULUM_RULE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DATE_MAPPING" for "TIMETABLE"."DATE_MAPPING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DATE_PATTERN" for "TIMETABLE"."DATE_PATTERN"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DATE_PATTERN_DEPT" for "TIMETABLE"."DATE_PATTERN_DEPT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DATE_PATTERN_PARENT" for "TIMETABLE"."DATE_PATTERN_PARENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DATE_PATTERN_PREF" for "TIMETABLE"."DATE_PATTERN_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DATE_PATTERN_SEQ" for "TIMETABLE"."DATE_PATTERN_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DEMAND_OFFR_TYPE" for "TIMETABLE"."DEMAND_OFFR_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DEPARTMENT" for "TIMETABLE"."DEPARTMENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DEPARTMENTAL_INSTRUCTOR" for "TIMETABLE"."DEPARTMENTAL_INSTRUCTOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DEPT_STATUS_TYPE" for "TIMETABLE"."DEPT_STATUS_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DEPT_TO_TT_MGR" for "TIMETABLE"."DEPT_TO_TT_MGR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DESIGNATOR" for "TIMETABLE"."DESIGNATOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DESIGNATOR_SEQ" for "TIMETABLE"."DESIGNATOR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DIST_OBJ_SEQ" for "TIMETABLE"."DIST_OBJ_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DIST_TYPE_DEPT" for "TIMETABLE"."DIST_TYPE_DEPT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DISTRIBUTION_OBJECT" for "TIMETABLE"."DISTRIBUTION_OBJECT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DISTRIBUTION_PREF" for "TIMETABLE"."DISTRIBUTION_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."DISTRIBUTION_TYPE" for "TIMETABLE"."DISTRIBUTION_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EGR_EGRESADO" for "EGRESADO"."EGR_EGRESADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EGR_EGRESADO_ARCHIVO" for "EGRESADO"."EGR_EGRESADO_ARCHIVO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EGR_EGRESADO_REQUISITO" for "EGRESADO"."EGR_EGRESADO_REQUISITO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EGR_PRACTICA_PREPR_DETALLE" for "EGRESADO"."EGR_PRACTICA_PREPR_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EGR_PRACTICA_PREPROFESIONAL" for "EGRESADO"."EGR_PRACTICA_PREPROFESIONAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EGR_REQUISITO" for "EGRESADO"."EGR_REQUISITO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EVENT" for "TIMETABLE"."EVENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EVENT_CONTACT" for "TIMETABLE"."EVENT_CONTACT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EVENT_JOIN_EVENT_CONTACT" for "TIMETABLE"."EVENT_JOIN_EVENT_CONTACT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EVENT_NOTE" for "TIMETABLE"."EVENT_NOTE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EVENT_NOTE_MEETING" for "TIMETABLE"."EVENT_NOTE_MEETING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXACT_TIME_MINS" for "TIMETABLE"."EXACT_TIME_MINS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM" for "TIMETABLE"."EXAM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM_INSTRUCTOR" for "TIMETABLE"."EXAM_INSTRUCTOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM_LOCATION_PREF" for "TIMETABLE"."EXAM_LOCATION_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM_OWNER" for "TIMETABLE"."EXAM_OWNER"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM_PERIOD" for "TIMETABLE"."EXAM_PERIOD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM_PERIOD_PREF" for "TIMETABLE"."EXAM_PERIOD_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM_ROOM_ASSIGNMENT" for "TIMETABLE"."EXAM_ROOM_ASSIGNMENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAM_TYPE" for "TIMETABLE"."EXAM_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXAUDIT" for "AUDITORIA"."EXAUDIT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXSEQ" for "AUDITORIA"."EXSEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXTERNAL_BUILDING" for "TIMETABLE"."EXTERNAL_BUILDING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXTERNAL_ROOM" for "TIMETABLE"."EXTERNAL_ROOM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXTERNAL_ROOM_DEPARTMENT" for "TIMETABLE"."EXTERNAL_ROOM_DEPARTMENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."EXTERNAL_ROOM_FEATURE" for "TIMETABLE"."EXTERNAL_ROOM_FEATURE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FEATURE_TYPE" for "TIMETABLE"."FEATURE_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_ASIGNACION" for "FINANZAS"."FIN_ASIGNACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_BENEFICIO" for "FINANZAS"."FIN_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_DETALLE_PAGO_TRAMITE" for "FINANZAS"."FIN_DETALLE_PAGO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_DETALLE_TRANSAC_PAGO" for "FINANZAS"."FIN_DETALLE_TRANSAC_PAGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_DETALLE_TRANSAC_PAGO_S" for "FINANZAS"."FIN_DETALLE_TRANSAC_PAGO_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_EJECUCION" for "FINANZAS"."FIN_EJECUCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_EJECUCION_DETALLE" for "FINANZAS"."FIN_EJECUCION_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_ESCALA" for "FINANZAS"."FIN_ESCALA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_MODALIDAD" for "FINANZAS"."FIN_MODALIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_MODALIDAD_ESCALA" for "FINANZAS"."FIN_MODALIDAD_ESCALA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_MODALIDAD_TASA" for "FINANZAS"."FIN_MODALIDAD_TASA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_OPERACION" for "FINANZAS"."FIN_OPERACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_OPERACION_TIPO_BENEFICIO" for "FINANZAS"."FIN_OPERACION_TIPO_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_PAGO_DETALLE_BOLETA" for "FINANZAS"."FIN_PAGO_DETALLE_BOLETA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_PAGO_DETALLE_CATEGORIA" for "FINANZAS"."FIN_PAGO_DETALLE_CATEGORIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_PREASIGNACION" for "FINANZAS"."FIN_PREASIGNACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_PROCESO" for "FINANZAS"."FIN_PROCESO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_TASA_BENEFICIO" for "FINANZAS"."FIN_TASA_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_TIPO_BENEFICIO" for "FINANZAS"."FIN_TIPO_BENEFICIO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_TIPO_BENEFICIO_EXCLUIDO" for "FINANZAS"."FIN_TIPO_BENEFICIO_EXCLUIDO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_TRANSAC_PENDIENTE_RESP" for "FINANZAS"."FIN_TRANSAC_PENDIENTE_RESP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FIN_TRANSAC_PENDIENTE_RESP_S" for "FINANZAS"."FIN_TRANSAC_PENDIENTE_RESP_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."FREE_TIME" for "TIMETABLE"."FREE_TIME"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_ALUMNO" for "GENERAL"."GEN_ALUMNO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_ALUMNO_CARNET" for "GENERAL"."GEN_ALUMNO_CARNET"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_AREA_FUNCIONAL" for "GENERAL"."GEN_AREA_FUNCIONAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_AULA" for "GENERAL"."GEN_AULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_AULA_DETALLE" for "GENERAL"."GEN_AULA_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_EMPLEADO" for "GENERAL"."GEN_EMPLEADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_EMPLEADO_AREAFUNCIONAL" for "GENERAL"."GEN_EMPLEADO_AREAFUNCIONAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_INSTITUCION" for "GENERAL"."GEN_INSTITUCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_INSTITUCION_EXTERNA" for "GENERAL"."GEN_INSTITUCION_EXTERNA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_INSTITUCION_SEDE" for "GENERAL"."GEN_INSTITUCION_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_INSTITUCION_SEDE_CONTACTO" for "GENERAL"."GEN_INSTITUCION_SEDE_CONTACTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_LOCAL" for "GENERAL"."GEN_LOCAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_MAESTRO_TABLAS" for "GENERAL"."GEN_MAESTRO_TABLAS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_MAESTRO_TABLAS_DETALLE" for "GENERAL"."GEN_MAESTRO_TABLAS_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_NOTIFICACION" for "GENERAL"."GEN_NOTIFICACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_PERSONA" for "GENERAL"."GEN_PERSONA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_PERSONA_FORMA_CONTACTAR" for "GENERAL"."GEN_PERSONA_FORMA_CONTACTAR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_SOLICITUD" for "GENERAL"."GEN_SOLICITUD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_SOLICITUD_ADJUNTA_DOC" for "GENERAL"."GEN_SOLICITUD_ADJUNTA_DOC"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_SOLICITUDDETALLE" for "GENERAL"."GEN_SOLICITUDDETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."GEN_TIPO_AULA" for "GENERAL"."GEN_TIPO_AULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."HISTORY" for "TIMETABLE"."HISTORY"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."HISTORY_SEQ" for "TIMETABLE"."HISTORY_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."HT_PREFERENCE" for "TIMETABLE"."HT_PREFERENCE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."INSTR_OFFERING_CONFIG" for "TIMETABLE"."INSTR_OFFERING_CONFIG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."INSTR_OFFR_CONFIG_SEQ" for "TIMETABLE"."INSTR_OFFR_CONFIG_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."INSTR_OFFR_PERMID_SEQ" for "TIMETABLE"."INSTR_OFFR_PERMID_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."INSTR_OFFR_SEQ" for "TIMETABLE"."INSTR_OFFR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."INSTRUCTIONAL_OFFERING" for "TIMETABLE"."INSTRUCTIONAL_OFFERING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."INSTRUCTOR_SEQ" for "TIMETABLE"."INSTRUCTOR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ITYPE_DESC" for "TIMETABLE"."ITYPE_DESC"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."JENRL" for "TIMETABLE"."JENRL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."JENRL_SEQ" for "TIMETABLE"."JENRL_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."LASTLIKE_COURSE_DEMAND" for "TIMETABLE"."LASTLIKE_COURSE_DEMAND"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."LOC_PERM_ID_SEQ" for "TIMETABLE"."LOC_PERM_ID_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."LOCATION_PICTURE" for "TIMETABLE"."LOCATION_PICTURE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."MANAGER_SETTINGS" for "TIMETABLE"."MANAGER_SETTINGS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."MAT_CONFIGURACION_MATRICULA" for "MATRICULA"."MAT_CONFIGURACION_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."MAT_MATRICULA_TURNO" for "MATRICULA"."MAT_MATRICULA_TURNO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."MAT_MATRICULA_TURNO_ALUMNO" for "MATRICULA"."MAT_MATRICULA_TURNO_ALUMNO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."MAT_PERMISO_MATRICULA" for "MATRICULA"."MAT_PERMISO_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."MEETING" for "TIMETABLE"."MEETING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."MESSAGE_LOG" for "TIMETABLE"."MESSAGE_LOG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."NON_UNIVERSITY_LOCATION" for "TIMETABLE"."NON_UNIVERSITY_LOCATION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."OFFERING_COORDINATOR" for "TIMETABLE"."OFFERING_COORDINATOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."OFFR_CONSENT_TYPE" for "TIMETABLE"."OFFR_CONSENT_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."OFFR_GROUP" for "TIMETABLE"."OFFR_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."OFFR_GROUP_OFFERING" for "TIMETABLE"."OFFR_GROUP_OFFERING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PK_PERMISO_MATRICULA" for "TRAMITE"."PK_PERMISO_MATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PK_SEGURIDAD" for "SEGURIDAD"."PK_SEGURIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PK_SOLICITUDIMPRESION" for "TRAMITE"."PK_SOLICITUDIMPRESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PKG_CALENDAR" for "CALENDAR"."PKG_CALENDAR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PMA_ALUMNO_CURSO" for "PREMATRICULA"."PMA_ALUMNO_CURSO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PMA_ALUMNO_CURSO_SESION" for "PREMATRICULA"."PMA_ALUMNO_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PMA_CONFI_PREMATRICULA" for "PREMATRICULA"."PMA_CONFI_PREMATRICULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PMA_CONFI_PREMATRICULA_B" for "PREMATRICULA"."PMA_CONFI_PREMATRICULA_B"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PMA_CONFI_PREMATRICULA_S" for "PREMATRICULA"."PMA_CONFI_PREMATRICULA_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."POS_ACAD_AREA_MAJOR" for "TIMETABLE"."POS_ACAD_AREA_MAJOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."POS_ACAD_AREA_MINOR" for "TIMETABLE"."POS_ACAD_AREA_MINOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."POS_MAJOR" for "TIMETABLE"."POS_MAJOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."POS_MAJOR_SEQ" for "TIMETABLE"."POS_MAJOR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."POS_MINOR" for "TIMETABLE"."POS_MINOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."POSITION_TYPE" for "TIMETABLE"."POSITION_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PREF_GROUP_SEQ" for "TIMETABLE"."PREF_GROUP_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PREF_LEVEL_SEQ" for "TIMETABLE"."PREF_LEVEL_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PREF_SEQ" for "TIMETABLE"."PREF_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PREFERENCE_LEVEL" for "TIMETABLE"."PREFERENCE_LEVEL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CLASE_PROGRAMADA" for "PROGRAMACION"."PRO_CLASE_PROGRAMADA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_EVALUACION" for "PROGRAMACION"."PRO_CURSO_EVALUACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_FORMULA" for "PROGRAMACION"."PRO_CURSO_FORMULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_FORMULA_BITACORA" for "PROGRAMACION"."PRO_CURSO_FORMULA_BITACORA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_FORMULA_TIPONOTA" for "PROGRAMACION"."PRO_CURSO_FORMULA_TIPONOTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_PERIODO" for "PROGRAMACION"."PRO_CURSO_PERIODO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_SECCION" for "PROGRAMACION"."PRO_CURSO_SECCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_SESION" for "PROGRAMACION"."PRO_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_SESION_REAPERTURA" for "PROGRAMACION"."PRO_CURSO_SESION_REAPERTURA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_CURSO_TIPONOTA" for "PROGRAMACION"."PRO_CURSO_TIPONOTA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_DIA_FERIADO" for "PROGRAMACION"."PRO_DIA_FERIADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_DOCENTE_REASIGNACION" for "PROGRAMACION"."PRO_DOCENTE_REASIGNACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_EVALUACION_PROGRAMADA" for "PROGRAMACION"."PRO_EVALUACION_PROGRAMADA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_EXAMEN_PROGRAMADO" for "PROGRAMACION"."PRO_EXAMEN_PROGRAMADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_MALLA_VIGENTE" for "PROGRAMACION"."PRO_MALLA_VIGENTE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_MATRICULA_CURSO_SESION" for "PROGRAMACION"."PRO_MATRICULA_CURSO_SESION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_MATRICULA_PERIODO" for "PROGRAMACION"."PRO_MATRICULA_PERIODO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_MATRICULAPERIODO_PRIORIDAD" for "PROGRAMACION"."PRO_MATRICULAPERIODO_PRIORIDAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_PERIODO" for "PROGRAMACION"."PRO_PERIODO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_PERIODO_RANGO_PRODUCTO" for "PROGRAMACION"."PRO_PERIODO_RANGO_PRODUCTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_PERIODO_RESULTADOCIERRE" for "PROGRAMACION"."PRO_PERIODO_RESULTADOCIERRE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_PERIODORANGO" for "PROGRAMACION"."PRO_PERIODORANGO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_RESERVA_AULA" for "PROGRAMACION"."PRO_RESERVA_AULA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_RESERVA_REPETICION" for "PROGRAMACION"."PRO_RESERVA_REPETICION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_SEMANA_DICTADO_PERIODO" for "PROGRAMACION"."PRO_SEMANA_DICTADO_PERIODO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_SOLICITUD_PROCESO" for "PROGRAMACION"."PRO_SOLICITUD_PROCESO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_SOLICITUD_PROCESO_BATCH" for "PROGRAMACION"."PRO_SOLICITUD_PROCESO_BATCH"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_TEMP_RESERVA" for "PROGRAMACION"."PRO_TEMP_RESERVA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."PRO_TRAMITE" for "PROGRAMACION"."PRO_TRAMITE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."QUERY_LOG" for "TIMETABLE"."QUERY_LOG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."QX__$TRIG_NUM" for "TIMETABLE"."QX__$TRIG_NUM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."REF_TABLE_SEQ" for "TIMETABLE"."REF_TABLE_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RELATED_COURSE_INFO" for "TIMETABLE"."RELATED_COURSE_INFO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RES_INTERVALO_DETALLE" for "RESERVA"."RES_INTERVALO_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RES_PLANIFICACION" for "RESERVA"."RES_PLANIFICACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RES_PLANIFICACION_DETALLE" for "RESERVA"."RES_PLANIFICACION_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RESERVATION" for "TIMETABLE"."RESERVATION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RESERVATION_CLASF" for "TIMETABLE"."RESERVATION_CLASF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RESERVATION_CLASS" for "TIMETABLE"."RESERVATION_CLASS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RESERVATION_CONFIG" for "TIMETABLE"."RESERVATION_CONFIG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RESERVATION_MAJOR" for "TIMETABLE"."RESERVATION_MAJOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RESERVATION_SEQ" for "TIMETABLE"."RESERVATION_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RESERVATION_STUDENT" for "TIMETABLE"."RESERVATION_STUDENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."RIGHTS" for "TIMETABLE"."RIGHTS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROLE_SEQ" for "TIMETABLE"."ROLE_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROLES" for "TIMETABLE"."ROLES"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM" for "TIMETABLE"."ROOM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_DEPT" for "TIMETABLE"."ROOM_DEPT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_DEPT_SEQ" for "TIMETABLE"."ROOM_DEPT_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_EXAM_TYPE" for "TIMETABLE"."ROOM_EXAM_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_FEATURE" for "TIMETABLE"."ROOM_FEATURE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_FEATURE_PREF" for "TIMETABLE"."ROOM_FEATURE_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_FEATURE_SEQ" for "TIMETABLE"."ROOM_FEATURE_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_GROUP" for "TIMETABLE"."ROOM_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_GROUP_PREF" for "TIMETABLE"."ROOM_GROUP_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_GROUP_ROOM" for "TIMETABLE"."ROOM_GROUP_ROOM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_GROUP_SEQ" for "TIMETABLE"."ROOM_GROUP_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_JOIN_ROOM_FEATURE" for "TIMETABLE"."ROOM_JOIN_ROOM_FEATURE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_PICTURE" for "TIMETABLE"."ROOM_PICTURE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_PREF" for "TIMETABLE"."ROOM_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_SEQ" for "TIMETABLE"."ROOM_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_SHARING_GROUP_SEQ" for "TIMETABLE"."ROOM_SHARING_GROUP_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_TYPE" for "TIMETABLE"."ROOM_TYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."ROOM_TYPE_OPTION" for "TIMETABLE"."ROOM_TYPE_OPTION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SAVED_HQL" for "TIMETABLE"."SAVED_HQL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SCHEDULING_SUBPART" for "TIMETABLE"."SCHEDULING_SUBPART"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SCRIPT" for "TIMETABLE"."SCRIPT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SCRIPT_PARAMETER" for "TIMETABLE"."SCRIPT_PARAMETER"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SECTIONING_COURSE_TYPES" for "TIMETABLE"."SECTIONING_COURSE_TYPES"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SECTIONING_INFO" for "TIMETABLE"."SECTIONING_INFO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SECTIONING_LOG" for "TIMETABLE"."SECTIONING_LOG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SECTIONING_QUEUE" for "TIMETABLE"."SECTIONING_QUEUE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SECTIONING_STATUS" for "TIMETABLE"."SECTIONING_STATUS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_APLICACION" for "SEGURIDAD"."SEG_APLICACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_APLICACION_CLIENT" for "SEGURIDAD"."SEG_APLICACION_CLIENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_APLICACION_OPCION_EXT" for "SEGURIDAD"."SEG_APLICACION_OPCION_EXT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_EMPLEADO_AREAFUNCROL" for "SEGURIDAD"."SEG_EMPLEADO_AREAFUNCROL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_MODULO" for "SEGURIDAD"."SEG_MODULO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_MODULO_APLICACION" for "SEGURIDAD"."SEG_MODULO_APLICACION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_OPCION" for "SEGURIDAD"."SEG_OPCION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_OPCION_ROL_SEDE" for "SEGURIDAD"."SEG_OPCION_ROL_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_ROL" for "SEGURIDAD"."SEG_ROL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_ROL_MODULO" for "SEGURIDAD"."SEG_ROL_MODULO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_ROL_SEDE" for "SEGURIDAD"."SEG_ROL_SEDE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_ROL_SEDE_CLIENTE" for "SEGURIDAD"."SEG_ROL_SEDE_CLIENTE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SEG_ROL_SEDE_PERSONA" for "SEGURIDAD"."SEG_ROL_SEDE_PERSONA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SESSION_CONFIG" for "TIMETABLE"."SESSION_CONFIG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SESSIONS" for "TIMETABLE"."SESSIONS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SETTINGS" for "TIMETABLE"."SETTINGS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SETTINGS_SEQ" for "TIMETABLE"."SETTINGS_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLUTION" for "TIMETABLE"."SOLUTION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLUTION_SEQ" for "TIMETABLE"."SOLUTION_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_GR_TO_TT_MGR" for "TIMETABLE"."SOLVER_GR_TO_TT_MGR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_GROUP" for "TIMETABLE"."SOLVER_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_GROUP_SEQ" for "TIMETABLE"."SOLVER_GROUP_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_INFO" for "TIMETABLE"."SOLVER_INFO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_INFO_DEF" for "TIMETABLE"."SOLVER_INFO_DEF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_INFO_DEF_SEQ" for "TIMETABLE"."SOLVER_INFO_DEF_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_INFO_SEQ" for "TIMETABLE"."SOLVER_INFO_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PARAMETER" for "TIMETABLE"."SOLVER_PARAMETER"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PARAMETER_DEF" for "TIMETABLE"."SOLVER_PARAMETER_DEF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PARAMETER_DEF_SEQ" for "TIMETABLE"."SOLVER_PARAMETER_DEF_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PARAMETER_GROUP" for "TIMETABLE"."SOLVER_PARAMETER_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PARAMETER_GROUP_SEQ" for "TIMETABLE"."SOLVER_PARAMETER_GROUP_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PARAMETER_SEQ" for "TIMETABLE"."SOLVER_PARAMETER_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PREDEF_SETTING" for "TIMETABLE"."SOLVER_PREDEF_SETTING"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SOLVER_PREDEF_SETTING_SEQ" for "TIMETABLE"."SOLVER_PREDEF_SETTING_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SP_XML_CURSO_INGRESANTE" for "TIMETABLE"."SP_XML_CURSO_INGRESANTE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SPONSORING_ORGANIZATION" for "TIMETABLE"."SPONSORING_ORGANIZATION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STAFF" for "TIMETABLE"."STAFF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STAFF_SEQ" for "TIMETABLE"."STAFF_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STANDARD_EVENT_NOTE" for "TIMETABLE"."STANDARD_EVENT_NOTE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT" for "TIMETABLE"."STUDENT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_ACAD_AREA" for "TIMETABLE"."STUDENT_ACAD_AREA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_ACCOMODATION" for "TIMETABLE"."STUDENT_ACCOMODATION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_CLASS_ENRL" for "TIMETABLE"."STUDENT_CLASS_ENRL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_CONFLICT_SEQ" for "TIMETABLE"."STUDENT_CONFLICT_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_ENRL" for "TIMETABLE"."STUDENT_ENRL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_ENRL_MSG" for "TIMETABLE"."STUDENT_ENRL_MSG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_ENRL_SEQ" for "TIMETABLE"."STUDENT_ENRL_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_GROUP" for "TIMETABLE"."STUDENT_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_GROUP_SEQ" for "TIMETABLE"."STUDENT_GROUP_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_INFO_SEQ" for "TIMETABLE"."STUDENT_INFO_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_MAJOR" for "TIMETABLE"."STUDENT_MAJOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_MINOR" for "TIMETABLE"."STUDENT_MINOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_SECT_HIST" for "TIMETABLE"."STUDENT_SECT_HIST"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_TO_ACOMODATION" for "TIMETABLE"."STUDENT_TO_ACOMODATION"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."STUDENT_TO_GROUP" for "TIMETABLE"."STUDENT_TO_GROUP"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SUBJECT_AREA" for "TIMETABLE"."SUBJECT_AREA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."SUBJECT_AREA_SEQ" for "TIMETABLE"."SUBJECT_AREA_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PATTERN" for "TIMETABLE"."TIME_PATTERN"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PATTERN_DAYS" for "TIMETABLE"."TIME_PATTERN_DAYS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PATTERN_DAYS_SEQ" for "TIMETABLE"."TIME_PATTERN_DAYS_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PATTERN_DEPT" for "TIMETABLE"."TIME_PATTERN_DEPT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PATTERN_SEQ" for "TIMETABLE"."TIME_PATTERN_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PATTERN_TIME" for "TIMETABLE"."TIME_PATTERN_TIME"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PATTERN_TIMES_SEQ" for "TIMETABLE"."TIME_PATTERN_TIMES_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIME_PREF" for "TIMETABLE"."TIME_PREF"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIMETABLE_GLOBAL_INFO_SEQ" for "TIMETABLE"."TIMETABLE_GLOBAL_INFO_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIMETABLE_INFO_SEQ" for "TIMETABLE"."TIMETABLE_INFO_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIMETABLE_MANAGER" for "TIMETABLE"."TIMETABLE_MANAGER"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIMETABLE_MGR_SEQ" for "TIMETABLE"."TIMETABLE_MGR_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIMETABLE_SEQ" for "TIMETABLE"."TIMETABLE_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TIMETABLE_SOLVER_PARAMETER_SEQ" for "TIMETABLE"."TIMETABLE_SOLVER_PARAMETER_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TMTBL_MGR_TO_ROLES" for "TIMETABLE"."TMTBL_MGR_TO_ROLES"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TMTBL_MGR_TO_ROLES_SEQ" for "TIMETABLE"."TMTBL_MGR_TO_ROLES_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_DOC_ACAD_CERTIFICADO" for "TRAMITE"."TRA_DOC_ACAD_CERTIFICADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_DOC_ACAD_CONSTANCIA" for "TRAMITE"."TRA_DOC_ACAD_CONSTANCIA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_PROCESO_PROGRAMADO" for "TRAMITE"."TRA_PROCESO_PROGRAMADO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_REG_MAS_DOC_ACAD_DETAL" for "TRAMITE"."TRA_REG_MAS_DOC_ACAD_DETAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_REG_MASIVO_DOC_ACAD_LOTE" for "TRAMITE"."TRA_REG_MASIVO_DOC_ACAD_LOTE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_ADJU_B" for "TRAMITE"."TRA_SOLI_TRAM_ADJU_B"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_ADJU_S" for "TRAMITE"."TRA_SOLI_TRAM_ADJU_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_DETA_B" for "TRAMITE"."TRA_SOLI_TRAM_DETA_B"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_DETA_S" for "TRAMITE"."TRA_SOLI_TRAM_DETA_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_EVEN_B" for "TRAMITE"."TRA_SOLI_TRAM_EVEN_B"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_EVEN_S" for "TRAMITE"."TRA_SOLI_TRAM_EVEN_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_EXTE_B" for "TRAMITE"."TRA_SOLI_TRAM_EXTE_B"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLI_TRAM_EXTE_S" for "TRAMITE"."TRA_SOLI_TRAM_EXTE_S"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLIC_DOCUMENTO_ACAD" for "TRAMITE"."TRA_SOLIC_DOCUMENTO_ACAD"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLICITUD_TRAMITE_ADJUNTO" for "TRAMITE"."TRA_SOLICITUD_TRAMITE_ADJUNTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLICITUD_TRAMITE_DETALLE" for "TRAMITE"."TRA_SOLICITUD_TRAMITE_DETALLE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLICITUD_TRAMITE_EVAL" for "TRAMITE"."TRA_SOLICITUD_TRAMITE_EVAL"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLICITUD_TRAMITE_EVENTO" for "TRAMITE"."TRA_SOLICITUD_TRAMITE_EVENTO"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLICITUD_TRAMITE_EXTEND" for "TRAMITE"."TRA_SOLICITUD_TRAMITE_EXTEND"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRA_SOLICITUD_TRAMITE_PREG" for "TRAMITE"."TRA_SOLICITUD_TRAMITE_PREG"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."TRAVEL_TIME" for "TIMETABLE"."TRAVEL_TIME"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."USER_DATA" for "TIMETABLE"."USER_DATA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."USER_SETTINGS_SEQ" for "TIMETABLE"."USER_SETTINGS_SEQ"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."USERS" for "TIMETABLE"."USERS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."V_SOL_DOC_ACAD_FULLDATA" for "TRAMITE"."V_SOL_DOC_ACAD_FULLDATA"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."VW_PERMISOS" for "SEGURIDAD"."VW_PERMISOS"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."WAITLIST" for "TIMETABLE"."WAITLIST"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."WF_FLOW" for "WORKFLOW"."WF_FLOW"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."WF_FLOWPROCEDURETYPE" for "WORKFLOW"."WF_FLOWPROCEDURETYPE"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."WF_FLOWTASK" for "WORKFLOW"."WF_FLOWTASK"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."WF_TASK" for "WORKFLOW"."WF_TASK"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."XCONFLICT" for "TIMETABLE"."XCONFLICT"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."XCONFLICT_EXAM" for "TIMETABLE"."XCONFLICT_EXAM"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."XCONFLICT_INSTRUCTOR" for "TIMETABLE"."XCONFLICT_INSTRUCTOR"';
        execute immediate 'CREATE OR REPLACE SYNONYM "UTEC"."XCONFLICT_STUDENT" for "TIMETABLE"."XCONFLICT_STUDENT"';
  dbms_output.put_line('----------------');
end;
/

set define off

declare
  type table_varchar  is table of varchar2(50);
  var_table_varchar  table_varchar;
  V_USER varchar2(50) := 'UTEC';
begin

  dbms_output.put_line('');
  dbms_output.put_line('UPDATE PENTAHO LINKS');
  dbms_output.put_line('----------------');


  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Aunitime_Reports%3Ahorarios%3Areporte_horarios.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 1;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'http://104.197.115.186:9500/pentaho/api/repos/%3Apublic%3AUnitime_Reports%3Acantidad_alumnos_matriculados_por_carrera%3Areporte_alumnos_carrera.wcdf/generatedContent?userid=unitime&password=d30ef02c-7fb1-4e00-a74b-82501bb2c695' where codreporte = 2;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'http://104.197.115.186:9500/pentaho/api/repos/%3Apublic%3AUnitime_Reports%3Acantidad_alumnos_matriculados_por_curso_sesion_seccion%3Areporte_alumno_cursessec.wcdf/generatedContent?userid=unitime&password=d30ef02c-7fb1-4e00-a74b-82501bb2c695' where codreporte = 3;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Acierre_ciclo%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 4;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_matriculados_por_tercera_vez%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 11;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aestado_cierre_cursos%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 12;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Amenciones_alumnos%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 14;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aequivalencias_registradas%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 15;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Acantidad_alumnos_matriculados_por_curso_sesion_seccion_edu%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 7;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Anotas_alumnos_por_periodo%3Anotas_alumnos_por_periodo.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 8;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Acantidad_alumnos_matriculados_por_carrera_edu%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 5;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Ahorarios_edu%3Areporte_horarios.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 6;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aformula_por_curso_edu%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 9;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Acarga_habil_por_periodo%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 16;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aconvalidaciones_por_periodo%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 17;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_pce_por_periodo%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 10;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_activos_por_curricula%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 13;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aseguimiento_notas_registradas%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 20;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aevaluaciones_pendientes%3Areport.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 18;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Asolicitudes_estado%3Areport.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 19;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aorden_merito_alumnos%3Aorden_merito_alumnos.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 23;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_riesgo_academico%3Areport.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 21;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Adetalle_formula_curso_por_periodo%3Adetalle_formula_curso_por_periodo.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 22;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aindicadores_tramite%3Areport-template.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 44;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aparciales_finales_pendientes%3Areport.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 25;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Asolicitudes_cambio_nota%3Areport.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 43;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Asunedu_carnets%3Asunedu_carnets.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 48;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_prematriculados%3Areporte_prematriculados.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 24;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_potencial_posibles_egresados%3Aalumnos_potencial_posibles_egresados.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 27;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_pce_disciplinario%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 42;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Asunedu_ingresantes%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 45;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Asunedu_matriculados%3Areporte.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 46;
  update CONFIGURACION.CON_REPORTES_UNITIME set url_link = 'https://analyticsqa.utec.edu.pe/pentaho/api/repos/%3Ahome%3Abasic%3Acdf-reports%3Aalumnos_matriculados_minedu%3Aalumnos_matriculados_minedu.wcdf/generatedContent?userid=basic&password=1b9a5d82-da15-11e7-9296-cec278b6b50a' where codreporte = 47;

  dbms_output.put_line('----------------');
end;
/


BEGIN
  dbms_session.reset_package;
end;
/

BEGIN
UPDATE
SEGURIDAD.SEG_APLICACION_CLIENT
SET
CLIENT = DBMS_RANDOM.string('x',20),
CLIENTSECRET = DBMS_RANDOM.string('x',20);
COMMIT;
END;
/
