        echo "> F            _____       "
        echo "> A         .-'     '-.    "
        echo "> I       .'           '.  "
        echo "> L      /   .      .    \ "
        echo "> E     :                 :"
        echo "> D     |                 |"
        echo ">       :      ____       :"
        echo ">        \   /      \    / "
        echo ">         '.           .'  "
        echo ">           '-._____.-'    "
        echo ">                          "[
