        echo "> "
        echo "> S            _____       "
        echo "> U         .-'     '-.    "
        echo "> C       .'           '.  "
        echo "> C      /   .      .    \ "
        echo "> E     :                 :"
        echo "> S     |                 |"
        echo "> S     :   \        /    :"
        echo ">        \   '.____.'    / "
        echo ">         '.           .'  "
        echo ">           '-._____.-'    "
        echo ">                          "
