-- =============================================================================
-- POC: PRUEBA DE FUEGO MEJORADA (TEST DE ROBUSTEZ Y ENGAÑO AL MOTOR)
-- Esquema objetivo: AST_DUMMY_APP
-- Ejecutar conectado como administrador (sys / system / astsysadmin)
-- =============================================================================

PROMPT =========================================================================
PROMPT 1) CREACIÓN DEL ESQUEMA DUMMY OBJETIVO (AST_DUMMY_APP)
PROMPT =========================================================================

DECLARE
  l_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_cnt FROM dba_users WHERE username = 'AST_DUMMY_APP';
  IF l_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER AST_DUMMY_APP CASCADE';
  END IF;
END;
/

CREATE USER AST_DUMMY_APP IDENTIFIED BY "DummyApp2026#"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

ALTER USER AST_DUMMY_APP QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE TO AST_DUMMY_APP;

PROMPT =========================================================================
PROMPT 2) CREACIÓN DE TABLAS OPERATIVAS Y COLUMNAS ENGAÑOSAS / BANCARIAS
PROMPT =========================================================================

-- Tabla principal de personas (contiene datos personales sensibles)
CREATE TABLE AST_DUMMY_APP.tbl_personas (
    dni             VARCHAR2(20)  NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    apellidos       VARCHAR2(150) NOT NULL,
    telefono        VARCHAR2(20),
    email           VARCHAR2(150),
    iban            VARCHAR2(30),   -- Columna Bancaria IBAN (Debe ser detectada automáticamente)
    cuenta_ccc      VARCHAR2(30),   -- Columna Bancaria CCC (Debe ser detectada automáticamente)
    nie_cif         VARCHAR2(20),   -- Documentos de identidad especiales (NIE/CIF)
    cod_dni_falso   VARCHAR2(20),   -- ENGAÑO: Se llama DNI pero tiene números secuenciales (no cumple patrón)
    correo_interno  VARCHAR2(50),   -- ENGAÑO: Se llama correo pero tiene textos "usuario_X" (no cumple patrón)
    CONSTRAINT pk_tbl_personas PRIMARY KEY (dni)
) TABLESPACE USERS;

-- Tabla de clientes (Tiene FK física que la une a tbl_personas)
CREATE TABLE AST_DUMMY_APP.tbl_clientes (
    cliente_id   NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    dni_ref      VARCHAR2(20)  NOT NULL,
    tipo_cliente VARCHAR2(50)  DEFAULT 'ESTÁNDAR',
    CONSTRAINT pk_tbl_clientes PRIMARY KEY (cliente_id),
    CONSTRAINT fk_cli_persona FOREIGN KEY (dni_ref) REFERENCES AST_DUMMY_APP.tbl_personas(dni)
) TABLESPACE USERS;

-- Tabla de empleados (Tiene FK física que la une a tbl_personas)
CREATE TABLE AST_DUMMY_APP.tbl_empleados (
    empleado_id  NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    dni_emp      VARCHAR2(20)  NOT NULL,
    cargo        VARCHAR2(100) NOT NULL,
    salario      NUMBER(10,2),
    CONSTRAINT pk_tbl_empleados PRIMARY KEY (empleado_id),
    CONSTRAINT fk_emp_persona FOREIGN KEY (dni_emp) REFERENCES AST_DUMMY_APP.tbl_personas(dni)
) TABLESPACE USERS;

-- Tabla de log de auditoría (Sin FK física por diseño, pero enlazada por lógica de negocio)
CREATE TABLE AST_DUMMY_APP.tbl_audit_log (
    log_id       NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    dni_usuario  VARCHAR2(20)  NOT NULL, -- DNI del usuario (relación lógica con tbl_personas.dni)
    accion       VARCHAR2(250) NOT NULL,
    fecha_accion TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_tbl_audit_log PRIMARY KEY (log_id)
) TABLESPACE USERS;

-- Tabla de historial de contacto (Sin FK física, conectada por email y teléfono a nivel de negocio)
CREATE TABLE AST_DUMMY_APP.tbl_historial_contacto (
    hist_id           NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    email_contacto    VARCHAR2(150), -- Relación lógica con tbl_personas.email
    telefono_contacto VARCHAR2(20),  -- Relación lógica con tbl_personas.telefono
    notes             VARCHAR2(4000),
    CONSTRAINT pk_tbl_hist_cont PRIMARY KEY (hist_id)
) TABLESPACE USERS;

-- Tabla de documentación (Para probar observaciones largas)
CREATE TABLE AST_DUMMY_APP.tbl_documentacion (
    doc_id           NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    dni_owner        VARCHAR2(20)  NOT NULL,
    nombre_archivo   VARCHAR2(250),           
    observaciones    VARCHAR2(4000),          -- Texto libre largo para probar IDENTIFICADOR_OBS
    datos_crudos     VARCHAR2(4000),          
    CONSTRAINT pk_tbl_documentacion PRIMARY KEY (doc_id),
    CONSTRAINT fk_doc_persona FOREIGN KEY (dni_owner) REFERENCES AST_DUMMY_APP.tbl_personas(dni)
) TABLESPACE USERS;

PROMPT =========================================================================
PROMPT 3) GENERACIÓN DE 110 REGISTROS (100 VÁLIDOS VÍA FPE + 10 SUCIOS)
PROMPT =========================================================================

DECLARE
  v_dni VARCHAR2(20);
  v_nombre VARCHAR2(100);
  v_apellido VARCHAR2(100);
  v_tel VARCHAR2(20);
  v_email VARCHAR2(150);
  v_iban VARCHAR2(30);
  v_cuenta VARCHAR2(30);
  v_nie_cif VARCHAR2(20);
  v_dni_falso VARCHAR2(20);
  v_correo_int VARCHAR2(50);
  v_letras VARCHAR2(23) := 'TRWAGMYFPDXBNJZSQVHLCKE';
  v_mod NUMBER;
  
  -- Para NIE/CIF
  v_nie_char CHAR(1);
  v_nie_num  VARCHAR2(7);
  v_cif_char CHAR(1);
  v_cif_num  VARCHAR2(7);
  
  -- Para IBAN
  v_bban   VARCHAR2(20);
  v_txt    VARCHAR2(30);
  v_rem    NUMBER;
  v_part   VARCHAR2(20);
  v_cc     VARCHAR2(2);
BEGIN
  -- 100 registros realistas
  FOR i IN 1..100 LOOP
    -- A) Generar DNI válido
    v_mod := MOD(12345000 + i, 23);
    v_dni := TO_CHAR(12345000 + i) || SUBSTR(v_letras, v_mod + 1, 1);
    
    -- B) Generar NIE y CIF válidos alternados
    IF MOD(i, 2) = 0 THEN
      -- NIE válido (X, Y o Z + 7 dígitos + letra de control)
      v_nie_char := CASE MOD(i, 3) WHEN 0 THEN 'X' WHEN 1 THEN 'Y' ELSE 'Z' END;
      v_nie_num  := TO_CHAR(9000000 + i);
      v_mod := MOD(TO_NUMBER(CASE v_nie_char WHEN 'X' THEN '0' WHEN 'Y' THEN '1' ELSE '2' END || v_nie_num), 23);
      v_nie_cif  := v_nie_char || v_nie_num || SUBSTR(v_letras, v_mod + 1, 1);
    ELSE
      -- CIF válido (Letra de tipo + 7 dígitos + dígito o letra de control)
      v_cif_char := CASE MOD(i, 4) WHEN 0 THEN 'A' WHEN 1 THEN 'B' WHEN 2 THEN 'E' ELSE 'H' END;
      v_cif_num  := LPAD(TO_CHAR(1000000 + i), 7, '0');
      DECLARE
        s_par NUMBER := 0;
        s_imp NUMBER := 0;
        d     NUMBER;
        x     NUMBER;
        c     NUMBER;
        l_tab CONSTANT VARCHAR2(10) := 'JABCDEFGHI';
        v_cif_ctrl CHAR(1);
      BEGIN
        FOR k IN 1 .. 7 LOOP
          d := TO_NUMBER(SUBSTR(v_cif_num,k,1));
          IF MOD(k,2)=0 THEN
            s_par := s_par + d;
          ELSE
            x := d*2;
            s_imp := s_imp + TRUNC(x/10) + MOD(x,10);
          END IF;
        END LOOP;
        c := MOD(10 - MOD(s_par+s_imp,10), 10);
        IF v_cif_char IN ('K','P','Q','S','N','W') THEN
          v_cif_ctrl := SUBSTR(l_tab,c+1,1);
        ELSIF v_cif_char IN ('A','B','E','H') THEN
          v_cif_ctrl := TO_CHAR(c);
        ELSE
          v_cif_ctrl := CASE WHEN MOD(c,2)=0 THEN TO_CHAR(c) ELSE SUBSTR(l_tab,c+1,1) END;
        END IF;
        v_nie_cif := v_cif_char || v_cif_num || v_cif_ctrl;
      END;
    END IF;

    -- C) Generar IBAN Español válido y con formato correcto (ES + 22 dígitos)
    v_bban := '21000418' || LPAD(TO_CHAR(100000000000 + i), 12, '0');
    v_txt  := v_bban || '142800';
    v_rem  := 0;
    FOR j IN 1 .. CEIL(LENGTH(v_txt)/7) LOOP
      v_part := TO_CHAR(v_rem) || SUBSTR(v_txt,(j-1)*7+1,7);
      v_rem  := MOD(TO_NUMBER(v_part),97);
    END LOOP;
    v_cc   := LPAD(TO_CHAR(98-v_rem),2,'0');
    v_iban := 'ES' || v_cc || v_bban;

    -- D) Generar Cuenta CCC válida (20 dígitos)
    v_cuenta := '1234567890' || LPAD(TO_CHAR(1000000000 + i), 10, '0');

    -- E) Datos de Engaño para el Motor de Descubrimiento
    v_dni_falso  := TO_CHAR(i);             -- Se llama "DNI" pero no tiene patrón de DNI (debe descartarse)
    v_correo_int := 'usuario_interno_'||i;  -- Se llama "correo" pero no tiene "@" (debe descartarse)

    -- F) Datos Personales Básicos
    v_nombre := CASE MOD(i, 5)
                  WHEN 0 THEN 'JUAN'
                  WHEN 1 THEN 'MARIA'
                  WHEN 2 THEN 'CARLOS'
                  WHEN 3 THEN 'ANA'
                  ELSE 'PEDRO'
                END || '_' || i;
    v_apellido := CASE MOD(i, 5)
                    WHEN 0 THEN 'GOMEZ'
                    WHEN 1 THEN 'LOPEZ'
                    WHEN 2 THEN 'PULIDO'
                    WHEN 3 THEN 'SANCHEZ'
                    ELSE 'SANZ'
                  END || ' ' || 
                  CASE MOD(i, 4)
                    WHEN 0 THEN 'FERNANDEZ'
                    WHEN 1 THEN 'DIAZ'
                    WHEN 2 THEN 'MARTIN'
                    ELSE 'PEREZ'
                  END;
                  
    v_tel := '6' || LPAD(TO_CHAR(i), 8, '0');
    v_email := LOWER(SUBSTR(v_nombre, 1, 3) || '.' || REPLACE(v_apellido, ' ', '.')) || '@correo.com';

    -- Insertar registros
    INSERT INTO AST_DUMMY_APP.tbl_personas (dni, nombre, apellidos, telefono, email, iban, cuenta_ccc, nie_cif, cod_dni_falso, correo_interno)
    VALUES (v_dni, v_nombre, v_apellido, v_tel, v_email, v_iban, v_cuenta, v_nie_cif, v_dni_falso, v_correo_int);
    
    INSERT INTO AST_DUMMY_APP.tbl_clientes (dni_ref, tipo_cliente)
    VALUES (v_dni, CASE MOD(i, 3) WHEN 0 THEN 'VIP' WHEN 1 THEN 'PREMIUM' ELSE 'ESTÁNDAR' END);
    
    INSERT INTO AST_DUMMY_APP.tbl_empleados (dni_emp, cargo, salario)
    VALUES (v_dni, 'PUESTO_OPERATIVO_' || i, 1500.00 + (i * 15));
    
    INSERT INTO AST_DUMMY_APP.tbl_audit_log (dni_usuario, accion)
    VALUES (v_dni, 'TRANSACCION_DE_PRUEBA_NUMERO_' || i);
    
    INSERT INTO AST_DUMMY_APP.tbl_historial_contacto (email_contacto, telefono_contacto, notes)
    VALUES (v_email, v_tel, 'Registro de auditoria para i=' || i);

    INSERT INTO AST_DUMMY_APP.tbl_documentacion (dni_owner, nombre_archivo, observaciones, datos_crudos)
    VALUES (
      v_dni, 
      'doc_factura_' || v_dni || '.pdf',
      'El cliente '|| v_nombre ||' solicita enmascarar su cuenta IBAN '|| v_iban ||' y su DNI '|| v_dni,
      '{"dni":"'||v_dni||'","nombre":"'||v_nombre||'","email":"'||v_email||'"}'
    );
  END LOOP;

  -- 10 registros sucios/de confusión
  FOR i IN 1..10 LOOP
    v_dni := CASE i
               WHEN 1 THEN 'DNI_ERR_'||i
               WHEN 2 THEN 'ABC'
               WHEN 3 THEN '123'
               ELSE '9999999' || i || 'Z'
             END;
    v_nie_cif := 'CIF_SUCIO_' || i;
    v_iban    := 'ES_IBAN_INVALIDO_' || i;
    v_cuenta  := 'CCC_INVALIDO_' || i;
    v_nombre := 'DIRTY_USER_' || i;
    v_apellido := 'DIRTY_SURNAME_' || i;
    v_tel := 'tel_letras_' || i;
    v_email := 'dirty_email_sin_arroba_' || i;
    v_dni_falso := 'falso_' || i;
    v_correo_int := 'correo_' || i;

    INSERT INTO AST_DUMMY_APP.tbl_personas (dni, nombre, apellidos, telefono, email, iban, cuenta_ccc, nie_cif, cod_dni_falso, correo_interno)
    VALUES (v_dni, v_nombre, v_apellido, v_tel, v_email, v_iban, v_cuenta, v_nie_cif, v_dni_falso, v_correo_int);
    
    INSERT INTO AST_DUMMY_APP.tbl_clientes (dni_ref, tipo_cliente)
    VALUES (v_dni, 'MOCK_SUSPENDIDO');
    
    INSERT INTO AST_DUMMY_APP.tbl_empleados (dni_emp, cargo, salario)
    VALUES (v_dni, 'MOCK_CARGO', 0.00);
    
    INSERT INTO AST_DUMMY_APP.tbl_audit_log (dni_usuario, accion)
    VALUES (v_dni, 'TRANSACCION_MOCK_SUCIA');
    
    INSERT INTO AST_DUMMY_APP.tbl_historial_contacto (email_contacto, telefono_contacto, notes)
    VALUES (v_email, v_tel, 'Notas de registro sucio ' || i);

    INSERT INTO AST_DUMMY_APP.tbl_documentacion (dni_owner, nombre_archivo, observaciones, datos_crudos)
    VALUES (
      v_dni,
      'archivo_sucio_' || i || '.docx',
      'Observacion corta ' || i,
      '{"dummy":"true"}'
    );
  END LOOP;

  COMMIT;
END;
/

PROMPT =========================================================================
PROMPT DUMMY SCHEMA CREADO CON EXITO (110 REGISTROS INSERTADOS POR TABLA)
PROMPT =========================================================================
PROMPT
PROMPT PASOS PARA PROBAR EL FLUJO COMPLETO EN LA BD (Conectado como ASTSYSADMIN):
PROMPT
PROMPT 1. Ejecutar el descubrimiento inicial usando el script wrapper:
PROMPT    @dm_descubre AST_DUMMY_APP Y
PROMPT
PROMPT 2. Consultar el catalogo descubierto y verificar el "Engaño":
PROMPT    SELECT table_name, column_name, identificador, enmascarar, ratio_match, score_total
PROMPT      FROM tdm_columna_final 
PROMPT     WHERE owner_name = 'AST_DUMMY_APP'
PROMPT     ORDER BY table_name, column_name;
PROMPT
PROMPT    *Nota:* Verifica que "COD_DNI_FALSO" y "CORREO_INTERNO" tengan enmascarar = 'N'
PROMPT    y puntuaciones bajas o descartadas, mientras que "IBAN" y "CUENTA_CCC"
PROMPT    tengan enmascarar = 'Y' con IDENTIFICADOR_BANCARIO.
PROMPT
PROMPT 3. Configurar las tablas SIN FK (Relacion logica de negocio):
PROMPT    UPDATE tdm_columna_final
PROMPT       SET enmascarar = 'Y', identificador = 'IDENTIFICADOR_IDENTIDAD'
PROMPT     WHERE owner_name = 'AST_DUMMY_APP'
PROMPT       AND table_name = 'TBL_AUDIT_LOG'
PROMPT       AND column_name = 'DNI_USUARIO';
PROMPT
PROMPT    UPDATE tdm_columna_final
PROMPT       SET enmascarar = 'Y', identificador = 'IDENTIFICADOR_EMAIL'
PROMPT     WHERE owner_name = 'AST_DUMMY_APP'
PROMPT       AND table_name = 'TBL_HISTORIAL_CONTACTO'
PROMPT       AND column_name = 'EMAIL_CONTACTO';
PROMPT
PROMPT    UPDATE tdm_columna_final
PROMPT       SET enmascarar = 'Y', identificador = 'IDENTIFICADOR_TELEFONO'
PROMPT     WHERE owner_name = 'AST_DUMMY_APP'
PROMPT       AND table_name = 'TBL_HISTORIAL_CONTACTO'
PROMPT       AND column_name = 'TELEFONO_CONTACTO';
PROMPT    COMMIT;
PROMPT
PROMPT 4. ESCENARIO DE INTEGRIDAD REFERENCIAL (Prueba de Re-inclusion A.2):
PROMPT    UPDATE tdm_columna_final
PROMPT       SET enmascarar = 'N'
PROMPT     WHERE owner_name = 'AST_DUMMY_APP'
PROMPT       AND table_name = 'TBL_CLIENTES'
PROMPT       AND column_name = 'DNI_REF';
PROMPT    COMMIT;
PROMPT
PROMPT 5. EJECUTAR EL PROCESO DE ENMASCARAMIENTO USANDO EL SCRIPT WRAPPER:
PROMPT    SELECT max(ejecucion_id) FROM tdm_ejecucion WHERE esquema_objetivo = 'AST_DUMMY_APP';
PROMPT    @dm_enmascara <EJECUCION_ID> Y
PROMPT
PROMPT 6. VALIDACIONES POST-MASQUERADE:
PROMPT    A) Comprobar re-inclusion por RI (Trazabilidad A.2):
PROMPT       SELECT paso, fase, detalle FROM tdm_mask_trace WHERE paso = 'RI_REINCLUYE';
PROMPT
PROMPT    B) Validar consistencia e inyectividad en DNI, NIE/CIF, IBAN y CCC:
PROMPT       SELECT dni, nie_cif, iban, cuenta_ccc FROM AST_DUMMY_APP.tbl_personas;
PROMPT
PROMPT    C) Validar que no hay nulos ni duplicados en el DNI enmascarado:
PROMPT       SELECT dni, COUNT(*) FROM AST_DUMMY_APP.tbl_personas GROUP BY dni HAVING COUNT(*) > 1;
PROMPT
PROMPT    D) Validar que el DNI del padre y del hijo coinciden exactamente (consistencia):
PROMPT       SELECT p.dni, c.dni_ref 
PROMPT         FROM AST_DUMMY_APP.tbl_personas p
PROMPT         JOIN AST_DUMMY_APP.tbl_clientes c ON c.dni_ref = p.dni;
PROMPT
PROMPT    E) Ejecutar validador de calidad:
PROMPT       @dm_validar_flujo AST_DUMMY_APP <EJECUCION_ID>
PROMPT
