SET ECHO ON;
SET SERVEROUTPUT ON;
SET NEWPAGE 0
SET SPACE 0
SET LINESIZE 32767
SET PAGESIZE 0
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET UNDERLINE OFF
SET HEADSEP OFF
SET LONG 10000
SET LONGC 10000
SET TRIMSPOOL ON
SET TERMOUT OFF
SET RECSEP OFF
select text from dba_source where name='PQ_IAA_UPDATESEQCPP' and owner='APP_IAA_COMUNES' and type='PACKAGE BODY';


SET ECHO ON;
SET SERVEROUTPUT ON;
SET NEWPAGE 0
SET SPACE 0
SET LINESIZE 32767
SET PAGESIZE 0
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET UNDERLINE OFF
SET HEADSEP OFF
SET LONG 10000
SET LONGC 10000
SET TRIMSPOOL ON
SET TERMOUT OFF
SET RECSEP OFF
select text from dba_source where name=upper('spu_refresco_scchemot_vm') and owner='SYS' and type='PROCEDURE';
