SET LINESIZE 150
SET PAGESIZE 100
COLUMN SEGMENT_TYPE FORMAT A20
COLUMN SIZE_GB FORMAT 999.999 "Size (GB)"

SELECT SEGMENT_TYPE,
       SUM(BYTES) / 1024 / 1024 / 1024 AS SIZE_GB
  FROM DBA_SEGMENTS
 WHERE OWNER = UPPER('&schema_name')
 GROUP BY SEGMENT_TYPE
 ORDER BY SIZE_GB DESC;

-- Total general
SELECT 'TOTAL' AS SEGMENT_TYPE,
       SUM(BYTES) / 1024 / 1024 / 1024 AS SIZE_GB
  FROM DBA_SEGMENTS
 WHERE OWNER = UPPER('&schema_name');
