
CREATE USER U_RIMAC IDENTIFIED BY UDQ9235FMA DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT TO U_RIMAC;
GRANT DBA TO U_RIMAC;
ALTER USER U_RIMAC DEFAULT ROLE ALL;
GRANT SELECT ANY DICTIONARY TO U_RIMAC;
GRANT SELECT ANY TABLE TO U_RIMAC;
GRANT UNLIMITED TABLESPACE TO U_RIMAC;
 
