SET pagesize 800
SET linesize 800
COL OPNAME FORMAT A15
COL USERNAME FORMAT A10
COL START_TIME FORMAT A14
COL END_TIME FORMAT A14
COL SEG FORMAT 999999
COL OBJETO FORMAT A5
COL SID FORMAT 999
COL SERIAL FORMAT 99999
COL BYTES 99999
COL BYTES_TOT FORMAT 99999999999
COL PCT FORMAT A6
COL TOT_HR FORMAT A9
COL TOT_MI FORMAT A10
COL FALTA FORMAT A14
select substr(OPNAME,0,15)OPNAME,USERNAME,TO_CHAR(START_TIME,'dd/mm hh24:mi:ss') START_TIME,TO_CHAR(LAST_UPDATE_TIME,'dd/mm hh24:mi:ss') END_TIME,ELAPSED_SECONDS SEG,
TARGET OBJETO,SID,SERIAL# SERIAL,SOFAR BYTES,TOTALWORK BYTES_TOT,
ROUND((SOFAR/TOTALWORK)*100,2)||'%' PCT,(ROUND(ELAPSED_SECONDS/60/60,2))||'Hrs.' TOT_HR,(ROUND(ELAPSED_SECONDS/60,2))||'Min.' TOT_MI,
(ROUND(TIME_REMAINING/60,2))||' Min.' FALTA
from v$session_longops where TOTALWORK> 0 and OPNAME LIKE '%RMAN%';
