set linesize 200
col host_name for a15
col open_mode for a20
col STATUS for a10
col OPEN_MODE for a10
select HOST_NAME,INSTANCE_NAME,INSTANCE_ROLE,VERSION,ACTIVE_STATE,STATUS,ARCHIVER,DATABASE_STATUS,OPEN_MODE,LOG_MODE,
TO_CHAR(CREATED,'DD-MM-YYYY HH24:mi') CREATE_DATE,TO_CHAR(STARTUP_TIME,'DD-MM-YYYY HH24:mi') STARTUP 
from v$instance, v$database;  

