#----- Recibe parametro nombre mes=MMYY
#-----
FECHA=`date +'%Y%m%d'`
FECHA_MES_ANT=$1
$ORACLE_HOME/bin/sqlplus -S mantenimiento/mn2013mn@BDDYNAP << EOF
set heading off
set termout off
set serveroutput off
set trimspool on
set linesize 1000 
set pagesize 500
set echo on
alter session set NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
alter session set current_schema=APP_RESTORE;
spool /oracle/backup/dmp/DDL_RESERVA_RIESGO_CURSO_ERP_${FECHA}.log
select 'Rename de tabla RESERVA_RIESGO_CURSO_ERP a RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}' from dual;
alter table  RESERVA_RIESGO_CURSO_ERP RENAME TO RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT};

select 'Creacion de Indices a la tabla RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}' from dual;
CREATE INDEX app_restore.IDX_RES_RIESGO_CURSO_ERP_${FECHA_MES_ANT} ON APP_RESTORE.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}
(IDEPOL)
LOGGING
TABLESPACE TBSI_RESTORE;

CREATE INDEX app_restore.IDX_RES_RIESGO_CURSO_ERP${FECHA_MES_ANT} ON APP_RESTORE.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}
(MONEDA, CODRAMO)
LOGGING
TABLESPACE TBSI_RESTORE;

CREATE INDEX app_restore.IX_RESERVA_RIESGO_C_FE_ER${FECHA_MES_ANT} ON APP_RESTORE.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}
(FECPRO)
LOGGING
TABLESPACE TBSI_RESTORE;

CREATE INDEX app_restore.IX_RESERVARIESGOCUR_ERP_0${FECHA_MES_ANT} ON APP_RESTORE.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}
(ANOPROC, MESPROC, CODRAMO)
LOGGING
TABLESPACE TBSI_RESTORE;

CREATE INDEX app_restore.IX_RESERVA_RIESGO_CURSO_E${FECHA_MES_ANT} ON APP_RESTORE.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}
(NUMOBLIG)
LOGGING
TABLESPACE TBSI_RESTORE;

select 'Creacion de Sinonimo RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}' from dual;
CREATE PUBLIC SYNONYM  RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT} for app_restore.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT};

select 'Permisos a tabla RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT} a sus respectivos roles del esquema APP_RESTORE' from dual;
GRANT select on app_restore.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT} to APP_RESTORE_SELECT;
GRANT insert on app_restore.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT} to APP_RESTORE_insert;
GRANT update on app_restore.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT} to APP_RESTORE_update;
GRANT delete on app_restore.RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT} to APP_RESTORE_delete;
 
select 'Ejecucion de Estadisticas a tabla RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}' from dual;
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('APP_RESTORE' , 'RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}');

select 'Validacion de Cantidad de Registros de la tabla RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT}' from dual;
select count(*) from RESERVA_RIESGO_CURSO_ERP_${FECHA_MES_ANT};

spool off
exit
EOF
